import 'package:cell_mobile/models/bio_entity.dart';
import 'package:flutter/material.dart';

import 'arcade/accelerator.dart';
import 'arcade/atom_builder.dart';
import 'arcade/big_bang_arcade.dart';
import 'arcade/collider.dart';
import 'arcade/corners.dart';
import 'arcade/hungry_cell.dart';
import 'arcade/organ_quiz.dart';
import 'arcade/molecule_mixer.dart';
import 'nothings/bit_memory/bit_memory_game.dart';
import 'somethings/whose_idea/whose_idea_game.dart';
import 'infinities/tangent/tangent_game.dart';
import 'infinities/area_under/area_under_game.dart';
import 'supply_chain/bottleneck/bottleneck_game.dart';
import 'supply_chain/stock_it/stock_it_game.dart';
import 'supply_chain/reroute/reroute_game.dart';
import 'supply_chain/build_chain/build_chain_game.dart';
import 'planets/orbit_ricochet/orbit_ricochet_game.dart';
import 'planets/orbit_pursuit/orbit_pursuit_game.dart';
import 'planets/orbit_slingshot/orbit_slingshot_game.dart';
import 'vocab/vocab_game.dart';
import 'vocab/vocab_banks.dart';
import 'financial/bonds/bonds_game.dart';
import 'galactic/spiral_arms/spiral_arms_game.dart';
import 'cosmic_structures/cosmic_web/cosmic_web_game.dart';
import 'financial/lobbying/lobbying_game.dart';
import 'galactic/black_hole/black_hole_game.dart';
import 'cosmic_structures/map_void/map_void_game.dart';
import 'farm_system/crop_rotation/crop_rotation_game.dart';
import 'galactic/galaxy_classify/galaxy_classify_game.dart';
import 'galactic/galaxy_merger/galaxy_merger_game.dart';
import 'financial/portfolio/portfolio_game.dart';
import 'farm_system/companion_planting/companion_planting_game.dart';
import 'cosmic_structures/structure_formation/structure_formation_game.dart';
import 'farm_system/sort_spuds/sort_spuds_game.dart';
import 'solar_systems/stellar_evolution/stellar_evolution_game.dart';
import 'cosmic_structures/lensing/lensing_game.dart';
import 'solar_systems/solar_storm/solar_storm_game.dart';
import 'farm_system/pest_patrol/pest_patrol_game.dart';
import 'solar_systems/space_rush/space_rush_game.dart';
import 'farm_system/pollination/pollination_game.dart';
import 'organelle/organelle_match/organelle_match_game.dart';
import 'tissue/twitch/twitch_game.dart';
import 'tissue/skin_layers/skin_layers_game.dart';
import 'organelle/membrane_gate/membrane_gate_game.dart';
import 'cell/cell_type/cell_type_game.dart';
import 'organelle/powerhouse/powerhouse_game.dart';
import 'tissue/tissue_type/tissue_type_game.dart';
import 'organ/heartbeat/heartbeat_game.dart';
import 'cell/osmosis/osmosis_game.dart';
import 'organ/nephron/nephron_game.dart';
import 'cell/transcribe/transcribe_game.dart';
import 'organ/body_map/body_map_game.dart';
import 'organ_system/circulate/circulate_game.dart';
import 'atoms/half_life/half_life_game.dart';
import 'organ_system/digest/digest_game.dart';
import 'organism/homeostasis/homeostasis_game.dart';
import 'molecular/phase_change/phase_change_game.dart';
import 'organism/life_cycle/life_cycle_game.dart';
import 'organ_system/reflex/reflex_game.dart';
import 'molecular/bond_lab/bond_lab_game.dart';
import 'ecosystem/food_web/food_web_game.dart';
import 'organism/forage/forage_game.dart';
import 'atoms/isotopes/isotopes_game.dart';
import 'atoms/electron_shells/electron_shells_game.dart';
import 'ecosystem/nutrient_cycle/nutrient_cycle_game.dart';
import 'molecular/ph_balance/ph_balance_game.dart';
import 'ecosystem/predator_prey/predator_prey_game.dart';
import 'nothings/quantum_foam/quantum_foam_game.dart';
import 'multiverse/bubbles/bubbles_game.dart';
import 'nothings/the_wait/the_wait_game.dart';
import 'multiverse/superposition/superposition_game.dart';
import 'universe_all/cosmic_timeline/cosmic_timeline_game.dart';
import 'particles/standard_model/standard_model_game.dart';
import 'infinities/converge/converge_game.dart';
import 'nothings/tzimtzum/tzimtzum_game.dart';
import 'particles/decay_chain/decay_chain_game.dart';
import 'multiverse/branch/branch_game.dart';
import 'somethings/pattern_lock/pattern_lock_game.dart';
import 'universe_all/constants/constants_game.dart';
import 'infinities/hilberts_hotel/hilberts_hotel_game.dart';
import 'universe_all/powers_of_ten/powers_of_ten_game.dart';
import 'supply_chain/delivery/delivery_game.dart';
import 'universe_all/everything/everything.dart';
import 'organism/harvest/harvest_game.dart';
import 'planets/orbit_catch/orbit_catch_game.dart';
import 'solar_systems/orbital_insertion/orbital_insertion_game.dart';
import 'multiverse/reality_merge/reality_merge_game.dart';
import 'financial/market_trader/market_trader.dart';
import 'package:cell_mobile/views/screens/mini_game_page/games/mitosis_rush_game.dart';
import 'package:cell_mobile/views/screens/mini_game_page/games/tissue_layer_game.dart';
import 'package:cell_mobile/views/screens/mini_game_page/games/organ_system_game.dart';
import 'package:cell_mobile/views/screens/mini_game_page/games/potato_rush_game.dart';
import 'package:cell_mobile/views/screens/mini_game_page/games/farm_panic_game.dart';
import 'mini_game.dart';

/// Canonical list of party-ready mini-games.
///
/// Every spec here is playable both from Explore (solo score attack) and
/// inside a party round (pass-and-play, highest score takes the round).
/// Scales without an enabled spec fall back to their legacy mini-game in
/// Explore and never appear in party rotation.
class MiniGameRegistry {
  MiniGameRegistry._();

  static final List<MiniGameSpec> specs = [
    MiniGameSpec(
      id: 'big_bang',
      name: 'Big Bang',
      scale: BioScale.nothings,
      tagline: 'Ignite matter out of the void',
      rules: [
        'Sparks of matter flash into the void — tap them before they fade: +10.',
        'Catch sparks back-to-back to build a combo, up to 5× points.',
        'Red antimatter detonates on touch: −15 and your combo resets.',
        'Halfway in, matter arrives in waves — 2×, then 4×, then 8× at the end. Catch what you can.',
      ],
      howToWin: 'Most matter when time runs out wins.',
      durationSeconds: 30,
      scoreUnit: 'matter',
      enabled: true,
      accent: const Color(0xFFFFAB40),
      icon: Icons.flare,
      // Tuned by playtest: ~150 = a solid run, ~320 = strong, ~520 = mastery
      // (sustained combos through the late-game waves). Also seeds CPU scaling.
      humanMax: 520,
      starThresholds: const [150, 320, 520],
      builder: (context, session) => BigBangArcade(session: session),
    ),
    MiniGameSpec(
      id: 'bit_memory',
      name: 'Bit Memory',
      scale: BioScale.somethings,
      tagline: 'Memorize the bits, then play them back — the string doubles each level',
      rules: [
        'Memorize the string of 0s and 1s shown.',
        'Tap GO to start answering early.',
        'Replay it in order on the 0 / 1 pad.',
        'One wrong bit ends the attempt.',
        'Right: +bits×10 and level up. Wrong: drop a level.',
      ],
      howToWin:
          'Bank the most points before time runs out — deeper strings pay exponentially more.',
      durationSeconds: 60,
      scoreUnit: 'points',
      enabled: true,
      accent: const Color(0xFF35D0BA),
      icon: Icons.memory,
      humanMax: 1500,
      starThresholds: const [300, 800, 1500],
      builder: (context, session) => BitMemoryGame(session: session),
    ),
    MiniGameSpec(
      id: 'corners',
      name: 'Corners',
      scale: BioScale.somethings,
      tagline: 'Count the corners, tap them true',
      rules: [
        'Outlined shapes appear — tap each one exactly as many times as it has corners.',
        'Your first tap claims a shape so it lasts longer; reach its corner count, then STOP.',
        'Closer counts score more — nail it exactly for a bonus.',
        'Later, rotating solids drift in: count the vertices as they spin.',
      ],
      howToWin: 'Most points when time runs out wins.',
      durationSeconds: 45,
      scoreUnit: 'points',
      enabled: true,
      accent: const Color(0xFF7E57C2),
      icon: Icons.category,
      builder: (context, session) => CornersGame(session: session),
    ),
    MiniGameSpec(
      id: 'whose_idea',
      name: 'Whose Idea?',
      scale: BioScale.somethings,
      tagline: 'Tap the mind history credits with the big idea',
      rules: [
        'A big idea appears with four historical thinkers.',
        'Tap the one credited with introducing it — faster answers score more.',
        'Build a streak for a multiplier; a context card drops after every answer.',
        'Attributions reflect accepted history — credit the winners wrote down.',
      ],
      howToWin: 'Most points when time runs out wins.',
      durationSeconds: 60,
      scoreUnit: 'points',
      enabled: true,
      accent: const Color(0xFFFFD600),
      icon: Icons.lightbulb_rounded,
      humanMax: 520,
      starThresholds: const [150, 320, 520],
      builder: (context, session) => WhoseIdeaGame(session: session),
    ),
    MiniGameSpec(
      id: 'collider',
      name: 'Collider',
      scale: BioScale.particles,
      tagline: 'Smash particles at the perfect moment',
      rules: [
        'Two particles race around the ring in opposite directions.',
        'Tap anywhere the instant they cross: perfect +25, close +10.',
        'Tap when they are apart: −5. Each collision speeds them up.',
      ],
      howToWin: 'Most collision points when time runs out wins.',
      durationSeconds: 45,
      scoreUnit: 'points',
      enabled: true,
      accent: const Color(0xFFAB47BC),
      icon: Icons.grain,
      builder: (context, session) => ColliderGame(session: session),
    ),
    MiniGameSpec(
      id: 'accelerator',
      name: 'Accelerator',
      scale: BioScale.particles,
      tagline: 'Pump the beam — hold the band — survive',
      rules: [
        'Tap anywhere to pump energy into the accelerator bar.',
        'Energy drains constantly — keep the needle inside the green band.',
        'Hold the band for 2.5 s to trigger a collision and score: +30 base plus a level bonus.',
        'Each level the band narrows and drain speeds up — find your rhythm.',
      ],
      howToWin: 'Most points when time runs out wins.',
      durationSeconds: 45,
      scoreUnit: 'points',
      enabled: true,
      accent: const Color(0xFFCE93D8),
      icon: Icons.bolt,
      builder: (context, session) => AcceleratorGame(session: session),
    ),
    MiniGameSpec(
      id: 'atom_builder',
      name: 'Atom Builder',
      scale: BioScale.atoms,
      tagline: 'Assemble elements particle by particle',
      rules: [
        'A target element is shown with the protons, neutrons and electrons it needs.',
        'Tap falling particles your atom still needs: +5 each.',
        'Tap a particle you do not need: −10. Complete an atom: +50 and a new target.',
      ],
      howToWin: 'Most points when time runs out wins.',
      durationSeconds: 45,
      scoreUnit: 'points',
      enabled: true,
      accent: const Color(0xFF5C6BC0),
      icon: Icons.blur_on,
      builder: (context, session) => AtomBuilderGame(session: session),
    ),
    MiniGameSpec(
      id: 'molecule_mixer',
      name: 'Molecule Mixer',
      scale: BioScale.molecular,
      tagline: 'Bond the right atoms, skip the rest',
      rules: [
        'A target molecule is shown (like H₂O = 2 hydrogen + 1 oxygen).',
        'Tap floating atoms the molecule still needs: +5 each.',
        'Wrong atom: −10. Complete a molecule: +30 and a new target appears.',
      ],
      howToWin: 'Most points when time runs out wins.',
      durationSeconds: 45,
      scoreUnit: 'points',
      enabled: true,
      accent: const Color(0xFF00BCD4),
      icon: Icons.science,
      builder: (context, session) => MoleculeMixerGame(session: session),
    ),
    MiniGameSpec(
      id: 'hungry_cell',
      name: 'Hungry Cell',
      scale: BioScale.organelle,
      tagline: 'Eat, grow, dodge — stay alive',
      rules: [
        'Drag anywhere to steer your cell.',
        'Eat green nutrients: +2 mass. Grab glowing organelles: +20 mass.',
        'Spiky viruses drain you: −15 mass on contact.',
      ],
      howToWin: 'Biggest mass gained when time runs out wins.',
      durationSeconds: 45,
      scoreUnit: 'mass',
      enabled: true,
      accent: const Color(0xFF9C27B0),
      icon: Icons.blur_circular,
      builder: (context, session) => HungryCellGame(session: session),
    ),
    MiniGameSpec(
      id: 'organ_rush',
      name: 'Organ Rush',
      scale: BioScale.organ,
      tagline: 'Name the part — human or potato — before the clock',
      rules: [
        'A clue appears: "The part that ..." with four options.',
        'Tap the right organ — the faster you answer, the more points.',
        'Questions alternate between human organs and plant (potato) organs.',
        'Build a streak for a multiplier; a fun fact drops after every answer.',
      ],
      howToWin: 'Most points when time runs out wins.',
      durationSeconds: 60,
      scoreUnit: 'points',
      enabled: true,
      accent: const Color(0xFF8BC34A),
      icon: Icons.quiz,
      builder: (context, session) => OrganQuizGame(session: session),
    ),
    MiniGameSpec(
      id: 'harvest',
      name: 'Harvest',
      scale: BioScale.organism,
      tagline: 'Grow them out, pull them at peak ripeness',
      rules: [
        'Potatoes ripen in their patches — tap one to harvest it.',
        'Riper pays more: a fully grown potato is worth far more than a green one.',
        'Golden potatoes pay double. Chain harvests for a combo multiplier.',
        'Spend coins on water (faster growth) and a helper that auto-harvests.',
      ],
      howToWin: 'Most points when time runs out wins.',
      durationSeconds: 60,
      scoreUnit: 'pts',
      humanMax: 250,
      // Tuned to humanMax: ~80 = a casual run, ~160 = ripe-timing dialed in,
      // ~250 = combo mastery. Feeds the 1–3 star payoff on the results screen.
      starThresholds: const [80, 160, 250],
      enabled: true,
      accent: const Color(0xFF66BB6A),
      icon: Icons.grass,
      builder: (context, session) => OrganismHarvestGame(session: session),
    ),
    MiniGameSpec(
      id: 'tangent',
      name: 'Tangent',
      scale: BioScale.infinities,
      tagline: 'Freeze the dot, read the slope — that slope is the derivative.',
      rules: [
        'Tap to freeze the dot on the curve.',
        'A tangent line snaps in at that point.',
        'Pick the slope (rise ÷ run) from four options.',
        'Correct = speed bonus × streak; wrong reveals the true slope.',
        'Curvier curves, faster dot, tighter options as time runs out.',
      ],
      howToWin: 'Highest score when the 60s clock ends.',
      durationSeconds: 60,
      scoreUnit: 'points',
      enabled: true,
      accent: const Color(0xFFE19816),
      icon: Icons.show_chart,
      humanMax: 1800,
      starThresholds: const [500, 1000, 1600],
      builder: (context, session) => TangentGame(session: session),
    ),
    MiniGameSpec(
      id: 'area_under',
      name: 'Area Under',
      scale: BioScale.infinities,
      tagline: 'Add rectangles until they become the integral',
      rules: [
        'A curve is drawn over [a, b]; the shaded area beneath it is the target.',
        'Slide to add Riemann rectangles — more rectangles hug the curve tighter.',
        'Your estimate closes in on the true area: the limit as n → ∞.',
        'Lock in once the MATCH meter clears the notch; tighter + faster scores more.',
      ],
      howToWin: 'Most points when time runs out wins.',
      durationSeconds: 60,
      scoreUnit: 'points',
      enabled: true,
      accent: const Color(0xFFE1C916),
      icon: Icons.area_chart_rounded,
      humanMax: 1400,
      starThresholds: const [450, 900, 1400],
      builder: (context, session) => AreaUnderGame(session: session),
    ),
    MiniGameSpec(
      id: 'mitosis_rush',
      name: 'Mitosis Rush',
      scale: BioScale.cell,
      tagline: 'Split the cell, race the clock',
      rules: [
        'Carry one cell through every phase of mitosis, in order.',
        'Each phase asks for a quick action — tap, match or pinch to advance.',
        'Move fast and clean: speed and accuracy both pay.',
        'Clear all the phases to finish the division early.',
      ],
      howToWin: 'Most points when the cycle ends wins.',
      durationSeconds: 75,
      scoreUnit: 'cells',
      enabled: true,
      accent: const Color(0xFF26A69A),
      icon: Icons.hub,
      builder: (context, session) => MitosisRushGame(session: session),
    ),
    MiniGameSpec(
      id: 'tissue_layer',
      name: 'Layer Builder',
      scale: BioScale.tissue,
      tagline: 'Stack the tissue layers in order',
      rules: [
        'Study the tissue, then rebuild it layer by layer from memory.',
        'Drop each cell into the right zone: correct placements score.',
        'Complete a whole organ for a bonus.',
        'Mistakes cost a life — keep the structure clean.',
      ],
      howToWin: 'Most points when time runs out wins.',
      durationSeconds: 45,
      scoreUnit: 'cells',
      enabled: true,
      accent: const Color(0xFF42A5F5),
      icon: Icons.layers,
      builder: (context, session) => TissueLayerGame(session: session),
    ),
    MiniGameSpec(
      id: 'organ_system',
      name: 'System Link',
      scale: BioScale.organSystem,
      tagline: 'Wire the organ systems together',
      rules: [
        'Route resources to the organs that need them before their health drains.',
        'Each delivery scores; chain them for a combo.',
        'Squish pests before they reach a node.',
        'Keep every organ alive — lose one and the round ends.',
      ],
      howToWin: 'Most points when time runs out wins.',
      durationSeconds: 60,
      scoreUnit: 'deliveries',
      enabled: true,
      accent: const Color(0xFF26C6DA),
      icon: Icons.account_tree,
      builder: (context, session) => OrganSystemGame(session: session),
    ),
    MiniGameSpec(
      id: 'potato_rush',
      name: 'Potato Rush',
      scale: BioScale.ecosystem,
      tagline: 'Keep the ecosystem in balance',
      rules: [
        'A fast gauntlet of micro-challenges — read each prompt and react.',
        'Clear a round to score and jump to the next, faster one.',
        'Three misses and the run is over.',
        'Survive the speed-up as long as you can.',
      ],
      howToWin: 'Most rounds cleared when time runs out wins.',
      durationSeconds: 45,
      scoreUnit: 'rounds',
      enabled: true,
      accent: const Color(0xFF66BB6A),
      icon: Icons.park,
      builder: (context, session) => PotatoRushGame(session: session),
    ),
    MiniGameSpec(
      id: 'farm_panic',
      name: 'Farm Panic',
      scale: BioScale.farmSystem,
      tagline: 'Run the farm before it runs you',
      rules: [
        'Swipe the underground channels sideways to keep water flowing.',
        'Tap glowing gold potatoes to harvest, tap weeds to yank, tap cash to bank.',
        'Swipe bugs to swat them before they reach the crop.',
        'Spend banked cash in the shop on Pesticide, Wind, Irrigation or a Farmhand.',
        'Chain actions for a combo; held cash slowly banks into your score.',
      ],
      howToWin: 'Most money (banked + earned) when time runs out wins.',
      durationSeconds: 60,
      scoreUnit: 'dollars',
      enabled: true,
      accent: const Color(0xFF9CCC65),
      icon: Icons.grass,
      builder: (context, session) => FarmPanicGame(session: session),
    ),
    MiniGameSpec(
      id: 'planet_catch',
      name: 'Orbit Catch',
      scale: BioScale.planets,
      tagline: 'Aim into the wells — gravity bends every shot',
      rules: [
        'Drag toward your target — your shot curves through gravity to reach it.',
        'Bigger wells pull harder — read the curve, then launch.',
        'Each catch scores; clear levels for bigger bonuses.',
        'Ten levels ramp the gravity and spacing, then loop harder.',
      ],
      howToWin: 'Most catches when time runs out wins.',
      durationSeconds: 60,
      scoreUnit: 'hits',
      enabled: true,
      accent: const Color(0xFF29B6F6),
      icon: Icons.public,
      humanMax: 2600,
      starThresholds: [900, 1700, 2600],
      builder: (context, session) => PlanetCatchGame(session: session),
    ),
    MiniGameSpec(
      id: 'orbit_ricochet',
      name: 'Ricochet',
      scale: BioScale.planets,
      tagline: 'Bank off walls and worlds — gravity bends, surfaces bounce',
      rules: [
        'Drag toward your target — your shot curves through gravity to reach it.',
        'Shots ricochet off planets, asteroids, and the arena walls.',
        'Bank into catchers tucked behind obstacles; each bounce adds bonus points.',
        'Ten levels ramp the field and shrink your flight time, then loop harder.',
      ],
      howToWin: 'Most catches when time runs out wins — bank shots score the most.',
      durationSeconds: 60,
      scoreUnit: 'banks',
      enabled: true,
      accent: const Color(0xFF7272AB),
      icon: Icons.sports_baseball,
      humanMax: 2900,
      starThresholds: const [1000, 1900, 2900],
      builder: (context, session) => OrbitRicochetGame(session: session),
    ),
    MiniGameSpec(
      id: 'orbit_pursuit',
      name: 'Pursuit',
      scale: BioScale.planets,
      tagline: 'Lead the moon — aim where it will be',
      rules: const [
        'Drag toward the target to launch; gravity curves the shot.',
        'The catcher moves — aim ahead of it, at the ghost dots.',
        'Catch every moon to clear the level; a miss costs a shot.',
        'Chain intercepts for a streak; faster targets score a lead bonus.',
      ],
      howToWin: 'Most intercepts when time runs out wins.',
      durationSeconds: 60,
      scoreUnit: 'intercepts',
      enabled: true,
      accent: const Color(0xFFE1C916),
      icon: Icons.track_changes,
      humanMax: 2600,
      starThresholds: const [700, 1500, 2400],
      builder: (context, session) => OrbitPursuitGame(session: session),
    ),
    MiniGameSpec(
      id: 'orbit_slingshot',
      name: 'Slingshot',
      scale: BioScale.planets,
      tagline: 'Chain gravity wells to whip a probe across the system',
      rules: [
        'Drag to aim — the drag points where the probe flies.',
        'Graze a well to slingshot: chain several to reach far.',
        'Longer chain = way more points (×assists²).',
        'Watch the preview: gold LOCK means you hit the beacon.',
      ],
      howToWin: 'Most beacons landed when time runs out wins.',
      durationSeconds: 60,
      scoreUnit: 'beacons',
      enabled: true,
      accent: const Color(0xFF7272AB),
      icon: Icons.rocket_launch,
      humanMax: 2200,
      starThresholds: const [600, 1300, 2200],
      builder: (context, session) => OrbitSlingshotGame(session: session),
    ),
    MiniGameSpec(
      id: 'orbital_insertion',
      name: 'Orbital Insertion',
      scale: BioScale.solarSystems,
      tagline: 'Fling a moon into a stable orbit',
      rules: [
        'Drag toward where you want the moon to go.',
        'Too slow it crashes; too fast it escapes.',
        'Just right captures it into orbit: +points.',
        'Rounder orbits score more and lap for bonus points.',
      ],
      howToWin: 'Most points when time runs out wins.',
      durationSeconds: 60,
      scoreUnit: 'points',
      enabled: true,
      accent: const Color(0xFF6690A3),
      icon: Icons.satellite_alt,
      humanMax: 3600,
      starThresholds: const [1300, 2400, 3600],
      builder: (context, session) => OrbitalInsertionGame(session: session),
    ),
    MiniGameSpec(
      id: 'reality_merge',
      name: 'Reality Merge',
      scale: BioScale.multiverseAll,
      tagline: 'Lock one dimension at a time to merge two realities',
      rules: [
        'A dim ghost ring shows the target reality.',
        'One property of your ring sweeps back and forth — TAP to lock it.',
        'Closer to the target = more points (Perfect / Great / OK).',
        'Lock every active property to MERGE; each merge adds a harder dimension.',
      ],
      howToWin: 'Highest sync score when time runs out wins.',
      durationSeconds: 45,
      scoreUnit: 'sync',
      enabled: true,
      accent: const Color(0xFF8A7BFF),
      icon: Icons.adjust,
      builder: (context, session) => RealityMergeGame(session: session),
    ),
    MiniGameSpec(
      id: 'everything',
      name: 'Everything Everywhere',
      scale: BioScale.universeAll,
      tagline: 'Name it in every tongue',
      rules: [
        'A word appears in a rotating language — type its English match.',
        'Answer before the word-timer empties.',
        'Faster answers and streaks score more.',
      ],
      howToWin: 'Most words when time runs out wins.',
      durationSeconds: 45,
      scoreUnit: 'words',
      enabled: true,
      accent: const Color(0xFF26A69A),
      icon: Icons.translate,
      builder: (context, session) => EverythingGame(session: session),
    ),
    MiniGameSpec(
      id: 'market_trader',
      name: 'Market Trader',
      scale: BioScale.financial,
      tagline: 'Size your trades, work the order book, bank profit',
      rules: [
        'Pick a lot size, then buy at market or rest a limit order.',
        'Limit orders reserve cash until the price drops to fill them.',
        'Cancel any order for a small fee to free reserves for a new play.',
        'Sell to realize profit — your closed P&L is the score.',
      ],
      howToWin: 'Most realized profit when the market closes wins.',
      durationSeconds: 60,
      scoreUnit: 'profit',
      enabled: true,
      accent: const Color(0xFFFFD54F),
      icon: Icons.show_chart,
      builder: (context, session) => FinancialTradingGame(session: session),
    ),
    MiniGameSpec(
      id: 'delivery',
      name: 'Delivery',
      scale: BioScale.supplyChain,
      tagline: 'Find the shortest route through every stop',
      rules: [
        'Drag from stop to stop to wire one continuous delivery route.',
        'Link every stop to finish the route — then a bigger one appears.',
        'You\'re scored on efficiency — your route length vs the best possible.',
        'Solve fast to bank a speed bonus and keep a streak alive.',
      ],
      howToWin: 'Most points when time runs out wins.',
      durationSeconds: 60,
      scoreUnit: 'pts',
      humanMax: 900,
      starThresholds: const [300, 600, 900],
      enabled: true,
      accent: const Color(0xFFFF7043),
      icon: Icons.route,
      builder: (context, session) => DeliveryGame(session: session),
    ),
    MiniGameSpec(
      id: 'bottleneck',
      name: 'Bottleneck',
      scale: BioScale.supplyChain,
      tagline: 'Boost the slow stage — keep the whole line shipping',
      rules: [
        'Potatoes flow Farm → Wash → Process → Store → Ship.',
        'A slow stage piles up (red BOTTLENECK) while stages after it starve.',
        'Tap the bottleneck to BOOST it; then it cools down briefly.',
        'Overflowing a bin rots potatoes — boosting a fast stage does nothing.',
      ],
      howToWin: 'Most potatoes shipped when time runs out wins.',
      durationSeconds: 60,
      scoreUnit: 'shipped',
      humanMax: 140,
      starThresholds: const [50, 95, 140],
      enabled: true,
      accent: const Color(0xFFE16416),
      icon: Icons.factory,
      builder: (context, session) => BottleneckGame(session: session),
    ),
    MiniGameSpec(
      id: 'stock_it',
      name: 'Stock It Right',
      scale: BioScale.supplyChain,
      tagline: 'Order ahead of the lead time — and beat the bullwhip.',
      rules: const [
        'Each DAY, demand sells potatoes off your shelf.',
        'ORDER to restock — it arrives only AFTER a lead time.',
        'Empty shelf = STOCKOUT penalty; too much = daily HOLDING cost.',
        'Keep stock in the healthy band; don\'t panic-order spikes.',
      ],
      howToWin: 'Most PROFIT when the 60 seconds run out wins.',
      durationSeconds: 60,
      scoreUnit: 'profit',
      enabled: true,
      accent: const Color(0xFF6690A3),
      icon: Icons.warehouse_rounded,
      humanMax: 3200,
      starThresholds: const [1200, 2200, 3000],
      builder: (context, session) => StockItGame(session: session),
    ),
    MiniGameSpec(
      id: 'reroute',
      name: 'Reroute!',
      scale: BioScale.supplyChain,
      tagline: 'Disruptions strike — reroute supply to keep the factory fed',
      rules: [
        'Goods flow from a source farm/port along the active route to your factory.',
        'Storms close routes and droughts empty sources — your supply line breaks.',
        'Tap a healthy source to reroute before the factory\'s silo starves.',
        'Cheap, close routes fail most — keep diverse backups ready.',
      ],
      howToWin: 'Most units produced when time runs out wins.',
      durationSeconds: 60,
      scoreUnit: 'units',
      humanMax: 150,
      starThresholds: const [60, 110, 150],
      enabled: true,
      accent: const Color(0xFF2EC4B6),
      icon: Icons.alt_route,
      builder: (context, session) => RerouteGame(session: session),
    ),
    MiniGameSpec(
      id: 'build_chain',
      name: 'Build the Chain',
      scale: BioScale.supplyChain,
      tagline: 'Assemble the potato supply chain — farm to customer, in order',
      rules: const [
        'Drag stage tiles into the slots in order: upstream → downstream.',
        'Right slot links the chain (teal); wrong slot breaks it (red arrow).',
        'Lock every stage in order, then keep potatoes flowing.',
        'Tap a stalled stage to clear it and keep goods moving.',
      ],
      howToWin: 'Assemble the most chains correctly before time runs out.',
      durationSeconds: 60,
      scoreUnit: 'links',
      enabled: true,
      accent: const Color(0xFFFF7043),
      icon: Icons.link,
      humanMax: 900,
      starThresholds: const [300, 600, 900],
      builder: (context, session) => BuildChainGame(session: session),
    ),
    MiniGameSpec(
      id: 'finance_vocab',
      name: 'Finance Lingo',
      scale: BioScale.financial,
      tagline: 'Match the definition to the right money term',
      rules: [
        'A definition appears with four candidate terms.',
        'Tap the term it describes — faster answers score more.',
        'The pace tightens as you go; build a streak for a multiplier.',
        'A card after every answer reinforces the term and its meaning.',
      ],
      howToWin: 'Most points when time runs out wins.',
      durationSeconds: 60,
      scoreUnit: 'points',
      enabled: true,
      accent: const Color(0xFF4CAF50),
      icon: Icons.savings_rounded,
      humanMax: 520,
      starThresholds: const [150, 320, 520],
      builder: (context, session) =>
          VocabGame(session: session, bank: kFinanceVocab),
    ),
    MiniGameSpec(
      id: 'bonds',
      name: 'Bonds',
      scale: BioScale.financial,
      tagline: 'When rates rise, bond prices fall — trade the seesaw',
      rules: [
        'Watch the INTEREST RATE ticker — bond prices move the OPPOSITE way.',
        'Tap a bond (2Y/5Y/10Y/30Y) to select it; set SIZE, then BUY.',
        'Buy when rates are high (prices cheap); SELL after rates fall and prices rise.',
        'Longer bonds swing harder — bigger profits and bigger losses (duration).',
        'Dump long bonds before rates climb. Close before the buzzer — only sold bonds score.',
      ],
      howToWin: 'Most realized profit when time runs out wins.',
      durationSeconds: 60,
      scoreUnit: 'profit',
      enabled: true,
      accent: const Color(0xFF7C9CB5),
      icon: Icons.show_chart,
      humanMax: 600,
      starThresholds: const [180, 380, 600],
      builder: (context, session) => BondsGame(session: session),
    ),
    MiniGameSpec(
      id: 'spiral_arms',
      name: 'Spiral Arms',
      scale: BioScale.galactic,
      tagline: 'A spinning galaxy shears its own arms apart — pulse on the beat to hold them',
      rules: [
        'The disk rotates differentially — inner stars outrun outer stars, so the arms keep shearing.',
        'A beat ring shrinks onto the target ring. Tap right as it lands: reinforce the wave, arms snap crisp.',
        'Chain on-beat pulses for up to a ×5 streak multiplier — that is where the points are.',
        'Off-beat or missed beats reset your streak and let the arms smear into a blank disk.',
        'It accelerates: faster spin, more arms, tighter timing.',
      ],
      howToWin: 'Highest score when time runs out — keep the arms crisp and chain clean pulses.',
      durationSeconds: 60,
      scoreUnit: 'coherence',
      enabled: true,
      accent: const Color(0xFFE1A636),
      icon: Icons.blur_circular,
      humanMax: 1600,
      starThresholds: const [450, 1000, 1600],
      builder: (context, session) => SpiralArmsGame(session: session),
    ),
    MiniGameSpec(
      id: 'cosmic_web',
      name: 'Cosmic Web',
      scale: BioScale.cosmicStructures,
      tagline: 'Trace the dark-matter filaments between superclusters',
      rules: [
        'Drag cluster → cluster along a faint filament.',
        'Real filament lights up and scores; a void link fails.',
        'Light every filament to complete the web.',
        'Each web is denser and fainter — go fast.',
      ],
      howToWin: 'Most points when time runs out wins.',
      durationSeconds: 60,
      scoreUnit: 'points',
      enabled: true,
      accent: const Color(0xFF7C5CFF),
      icon: Icons.hub,
      humanMax: 2000,
      starThresholds: const [700, 1400, 2000],
      builder: (context, session) => CosmicWebGame(session: session),
    ),
    MiniGameSpec(
      id: 'lobbying',
      name: 'Lobbying',
      scale: BioScale.financial,
      tagline: 'Spend influence, swing the vote, bank the payout',
      rules: [
        'A bill needs a majority of officials voting YES to pass.',
        'Tap an official to spend influence and raise their yes-chance.',
        'Diminishing returns — overspending one official wastes cash and risks scandal.',
        'Pass bills before the vote timer runs out; each payout is your score.',
      ],
      howToWin: 'Most payouts banked when time runs out wins.',
      durationSeconds: 60,
      scoreUnit: 'influence',
      enabled: true,
      accent: const Color(0xFF9CCC65),
      icon: Icons.account_balance,
      humanMax: 1800,
      starThresholds: const [600, 1100, 1800],
      builder: (context, session) => LobbyingGame(session: session),
    ),
    MiniGameSpec(
      id: 'black_hole',
      name: 'Black-Hole Heart',
      scale: BioScale.galactic,
      tagline: 'Orbit the abyss — close is fast, close is fatal',
      rules: [
        'Drag to fling a star; the drag is its launch velocity.',
        'Too slow falls past the event horizon; too fast escapes.',
        'Tighter, faster orbits score more but decay faster.',
        'Survive gravitational kicks as the safe zone tightens.',
      ],
      howToWin: 'Most points when time runs out wins.',
      durationSeconds: 60,
      scoreUnit: 'points',
      enabled: true,
      accent: const Color(0xFF8B5CF6),
      icon: Icons.filter_tilt_shift,
      humanMax: 6000,
      starThresholds: const [2200, 4200, 6000],
      builder: (context, session) => BlackHoleGame(session: session),
    ),
    MiniGameSpec(
      id: 'map_void',
      name: 'Map the Void',
      scale: BioScale.cosmicStructures,
      tagline: 'Tag the sky: cluster, filament, or void',
      rules: [
        'A survey scope frames one region — read its galaxy density.',
        'Tap CLUSTER (dense knot), FILAMENT (thread), or VOID (empty).',
        'Faster correct tags score more; streak builds a multiplier.',
        'Most of the universe is VOID — don\'t over-tag structure.',
      ],
      howToWin: 'Most correctly-classified regions when time runs out wins.',
      durationSeconds: 60,
      scoreUnit: 'regions',
      enabled: true,
      accent: const Color(0xFF7C5CFF),
      icon: Icons.travel_explore_rounded,
      humanMax: 2600,
      starThresholds: const [700, 1500, 2400],
      builder: (context, session) => MapVoidGame(session: session),
    ),
    MiniGameSpec(
      id: 'crop_rotation',
      name: 'Crop Rotation',
      scale: BioScale.farmSystem,
      tagline: 'Rotate the families — keep the soil alive',
      rules: [
        'Tap a crop, then tap fields to plant it; GROW to harvest the season.',
        'Watch each field\'s nitrogen bar: legumes (beans) restore it, corn drains it.',
        'Repeat a family on a field and yield, soil and pests all crash.',
        'Rotate families — and plant roots (potatoes) to break pest cycles.',
      ],
      howToWin: 'Most total harvest yield when time runs out wins.',
      durationSeconds: 60,
      scoreUnit: 'harvest',
      enabled: true,
      accent: const Color(0xFF8BC34A),
      icon: Icons.agriculture,
      humanMax: 2600,
      starThresholds: const [700, 1500, 2400],
      builder: (context, session) => CropRotationGame(session: session),
    ),
    MiniGameSpec(
      id: 'galaxy_classify',
      name: 'Galaxy Classifier',
      scale: BioScale.galactic,
      tagline: 'Read the sky — sort each galaxy by its shape',
      rules: [
        'Tap the type of the framed galaxy — fast calls score most (+120).',
        'Spot the shape: Spiral · Barred Spiral · Elliptical · Irregular.',
        'Chain correct calls for a ×streak; wrong or missed reveals the truth.',
      ],
      howToWin: 'Most galaxies correctly classified when time runs out wins.',
      durationSeconds: 60,
      scoreUnit: 'galaxies',
      enabled: true,
      accent: const Color(0xFF7C6FF0),
      icon: Icons.auto_awesome,
      humanMax: 6500,
      starThresholds: const [1800, 3600, 5500],
      builder: (context, session) => GalaxyClassifyGame(session: session),
    ),
    MiniGameSpec(
      id: 'galaxy_merger',
      name: 'Galaxy Merger',
      scale: BioScale.galactic,
      tagline: 'Graze two galaxies into one — mind the tidal tails',
      rules: [
        'Drag to aim the incoming galaxy: direction + speed.',
        'Slow grazing pass merges the cores: big points.',
        'Sweep the streaming tidal tails through gold zones: +12 each.',
        'Too fast = flyby — stars scatter, streak resets.',
      ],
      howToWin: 'Most stars when time runs out — chain clean merges.',
      durationSeconds: 60,
      scoreUnit: 'stars',
      enabled: true,
      accent: const Color(0xFF7272AB),
      icon: Icons.blur_circular,
      humanMax: 2600,
      starThresholds: const [900, 1700, 2500],
      builder: (context, session) => GalaxyMergerGame(session: session),
    ),
    MiniGameSpec(
      id: 'portfolio',
      name: 'Portfolio',
      scale: BioScale.financial,
      tagline: 'Spread your bets — diversify to survive the crash',
      rules: [
        'Split your \$1,000 across volatile stocks and one steady index ETF.',
        'Tap − / + to set weights, or SPREAD EVENLY / ALL-IN ETF in one tap.',
        'Sector crashes wipe a concentrated bet — a diversified book shrugs them off.',
        'Your portfolio value is the score; grow it without blowing up.',
      ],
      howToWin: 'Highest portfolio value when the market closes wins.',
      durationSeconds: 60,
      scoreUnit: 'value',
      enabled: true,
      accent: const Color(0xFF4DB6AC),
      icon: Icons.pie_chart,
      humanMax: 2600,
      starThresholds: const [1300, 1900, 2800],
      builder: (context, session) => PortfolioGame(session: session),
    ),
    MiniGameSpec(
      id: 'companion_planting',
      name: 'Companion Planting',
      scale: BioScale.farmSystem,
      tagline: 'Arrange the bed so neighbours help, not hurt',
      rules: [
        'Drag crop tiles onto the garden grid — only up/down/left/right neighbours interact.',
        'Friendly pairs (corn+beans+squash, marigold/basil+tomato) score +helps; combos pay more.',
        'Bad neighbours wilt — keep fennel and potato+tomato apart: −hurts breaks your combo.',
        'Fill the plot, then the growth phase rewards well-surrounded plants and flawless beds.',
      ],
      howToWin: 'Most points when time runs out — flawless, foe-free plots pay the biggest bonus.',
      durationSeconds: 60,
      scoreUnit: 'points',
      enabled: true,
      accent: const Color(0xFF7CB342),
      icon: Icons.grass,
      humanMax: 900,
      starThresholds: const [250, 500, 900],
      builder: (context, session) => CompanionPlantingGame(session: session),
    ),
    MiniGameSpec(
      id: 'structure_formation',
      name: 'Structure Formation',
      scale: BioScale.cosmicStructures,
      tagline: 'Seed tiny ripples; let gravity weave the cosmic web',
      rules: [
        'Tap to seed a density fluctuation.',
        'Gravity grows over-densities into clusters.',
        'Spread seeds — over-seeding one spot wastes it.',
        'Beat expansion and the late dark-energy surge.',
      ],
      howToWin: 'Collapse the most mass into a well-formed web before time runs out.',
      durationSeconds: 60,
      scoreUnit: 'mass',
      enabled: true,
      accent: const Color(0xFF8E6BFF),
      icon: Icons.grain,
      humanMax: 1400,
      starThresholds: const [400, 800, 1300],
      builder: (context, session) => StructureFormationGame(session: session),
    ),
    MiniGameSpec(
      id: 'sort_spuds',
      name: 'Sort the Spuds',
      scale: BioScale.farmSystem,
      tagline: 'Grade the good, cull the rotten — before the belt beats you',
      rules: [
        'Tap SMALL / MEDIUM / LARGE for the gold-ringed spud.',
        'Cull rotten / green / blemished spuds into REJECT.',
        'Rotten in a sale bin contaminates the crate: big penalty.',
        'Sort before it falls off the end of the belt.',
      ],
      howToWin: 'Most points when the timer runs out wins.',
      durationSeconds: 60,
      scoreUnit: 'graded',
      enabled: true,
      accent: const Color(0xFFE19816),
      icon: Icons.grading,
      humanMax: 850,
      starThresholds: const [300, 550, 800],
      builder: (context, session) => SortSpudsGame(session: session),
    ),
    MiniGameSpec(
      id: 'stellar_evolution',
      name: 'Stellar Evolution',
      scale: BioScale.solarSystems,
      tagline: 'Mass decides a star\'s fate',
      rules: [
        'Guide one star through its life, one quick tap-action per phase.',
        'Mash to collapse the nebula; time the ignition and the supernova.',
        'Balance gravity vs fusion to hold the main sequence.',
        'Mass branches the path: white dwarf, or supernova → neutron star / black hole.',
      ],
      howToWin: 'Most points when time runs out wins.',
      durationSeconds: 60,
      scoreUnit: 'points',
      enabled: true,
      accent: const Color(0xFFB388FF),
      icon: Icons.auto_awesome,
      humanMax: 900,
      starThresholds: const [300, 600, 900],
      builder: (context, session) => StellarEvolutionGame(session: session),
    ),
    MiniGameSpec(
      id: 'lensing',
      name: 'Lensing',
      scale: BioScale.cosmicStructures,
      tagline: 'Bend a galaxy\'s light home with invisible mass',
      rules: const [
        'Drag the dark-matter halo into the light\'s path.',
        'Slide MASS: too little flies past, too much over-bends.',
        'Curve the rays onto the detector — gold rays = focused.',
        'Hold the focus to take the reading; two galaxies = Einstein ring.',
      ],
      howToWin: 'Most readings focused before time runs out wins.',
      durationSeconds: 60,
      scoreUnit: 'readings',
      enabled: true,
      accent: const Color(0xFF7272AB),
      icon: Icons.lens_blur,
      humanMax: 4200,
      starThresholds: const [1400, 2600, 3800],
      builder: (context, session) => LensingGame(session: session),
    ),
    MiniGameSpec(
      id: 'solar_storm',
      name: 'Solar Storm',
      scale: BioScale.solarSystems,
      tagline: 'Tame the Sun before its storms reach Earth',
      rules: [
        'Tap sunspots to quell them — early scores more.',
        'Tap incoming flares & CMEs to raise shields.',
        'Catch storms high; a belt hit damages the grid.',
        'Solar cycle ramps to maximum: faster, more, at once.',
      ],
      howToWin: 'Most points when the 60s solar cycle ends wins.',
      durationSeconds: 60,
      scoreUnit: 'points',
      enabled: true,
      accent: const Color(0xFFE16416),
      icon: Icons.wb_sunny,
      humanMax: 850,
      starThresholds: const [300, 550, 800],
      builder: (context, session) => SolarStormGame(session: session),
    ),
    MiniGameSpec(
      id: 'pest_patrol',
      name: 'Pest Patrol',
      scale: BioScale.farmSystem,
      tagline: 'Match the predator, save the crop',
      rules: const [
        'Pests march down and eat your crop — clear them fast.',
        'Arm a beneficial, tap the field to release it on its match.',
        'Ladybug→Aphid · Lacewing→Mite · Bird→Caterpillar.',
        'Spray kills ALL pests but also your helpers + bees, and breeds resistance.',
      ],
      howToWin: 'Most crops saved when time runs out wins.',
      durationSeconds: 60,
      scoreUnit: 'crops',
      enabled: true,
      accent: const Color(0xFF8BC34A),
      icon: Icons.pest_control_outlined,
      humanMax: 800,
      starThresholds: const [250, 500, 750],
      builder: (context, session) => PestPatrolGame(session: session),
    ),
    MiniGameSpec(
      id: 'space_rush',
      name: 'Space Rush',
      scale: BioScale.solarSystems,
      tagline: 'A gauntlet of worlds — react before warp speed',
      rules: const [
        'Read the one-word prompt, then react fast.',
        'Clear the microgame before the timer: +1.',
        'DODGE asteroids, CATCH comet dust, LAND on the Moon.',
        'SPIN a gas giant, SORT dwarfs, TILT an axis, pop FLARES.',
        'Three misses ends the run — survive the speed-up.',
      ],
      howToWin: 'Clear the most microgames before time or your lives run out.',
      durationSeconds: 60,
      scoreUnit: 'clears',
      enabled: true,
      accent: const Color(0xFF5C7CFA),
      icon: Icons.rocket_launch,
      humanMax: 28,
      starThresholds: const [10, 18, 26],
      builder: (context, session) => SpaceRushGame(session: session),
    ),
    MiniGameSpec(
      id: 'pollination',
      name: 'Pollination Dash',
      scale: BioScale.farmSystem,
      tagline: 'Carry pollen flower to flower before the blooms wilt',
      rules: [
        'Drag to steer the bee — it flies toward your finger.',
        'Touch a flower to pick up its pollen.',
        'Touch ANOTHER flower of the same color to pollinate it and set fruit.',
        'Chain same-color flowers for a combo; dodge pesticide clouds and wind.',
      ],
      howToWin: 'Most fruit set when time runs out wins.',
      durationSeconds: 60,
      scoreUnit: 'fruit set',
      enabled: true,
      accent: const Color(0xFFEF5DA8),
      icon: Icons.local_florist,
      humanMax: 2000,
      starThresholds: const [500, 1000, 1600],
      builder: (context, session) => PollinationGame(session: session),
    ),
    MiniGameSpec(
      id: 'organelle_match',
      name: 'Organelle Match',
      scale: BioScale.organelle,
      tagline: 'Name the worker behind the job',
      rules: const [
        'A clue names a job: tap the organelle that does it.',
        'Faster answers score more — the speed window tightens as you go.',
        'Chain correct answers: every 3 in a row adds +1x multiplier.',
        'A miss just resets the streak — no penalty. Read the fact, push on.',
      ],
      howToWin: 'Most points when time runs out wins.',
      durationSeconds: 60,
      scoreUnit: 'points',
      enabled: true,
      accent: const Color(0xFF3DDC97),
      icon: Icons.hub_rounded,
      humanMax: 1800,
      starThresholds: const [500, 1000, 1600],
      builder: (context, session) => OrganelleMatchGame(session: session),
    ),
    MiniGameSpec(
      id: 'membrane_gate',
      name: 'Membrane Gate',
      scale: BioScale.organelle,
      tagline: 'Let the right molecules in — keep the toxins out',
      rules: [
        'Tap the molecules the cell NEEDS (O₂, water, ions, glucose): +10.',
        'Build a streak for a multiplier — every 5 in a row raises it.',
        'Do NOT tap toxins, viruses or waste — let them bounce off the membrane.',
        'Tapping a toxin lets it in: −8 and your streak resets.',
      ],
      howToWin: 'Most molecules imported when time runs out wins.',
      durationSeconds: 60,
      scoreUnit: 'molecules',
      enabled: true,
      accent: const Color(0xFF4FC3F7),
      icon: Icons.sensor_door,
      humanMax: 800,
      starThresholds: const [280, 520, 760],
      builder: (context, session) => MembraneGateGame(session: session),
    ),
    MiniGameSpec(
      id: 'twitch',
      name: 'Twitch',
      scale: BioScale.tissue,
      tagline: 'Fire the muscle on the beat of the nerve',
      rules: [
        'A nerve signal races to the junction — tap as it hits the strike zone to fire.',
        'Dead-center timing scores most; on-time taps chain a streak multiplier.',
        'Mistimed taps or signals you let pass are wasted — the streak resets.',
        'Fire fast so twitches summate past the TETANUS line for bonus force.',
      ],
      howToWin: 'Most force when time runs out wins.',
      durationSeconds: 60,
      scoreUnit: 'force',
      enabled: true,
      accent: const Color(0xFFE05260),
      icon: Icons.bolt,
      humanMax: 3200,
      starThresholds: const [1100, 2100, 3000],
      builder: (context, session) => TwitchGame(session: session),
    ),
    MiniGameSpec(
      id: 'skin_layers',
      name: 'Skin Layers',
      scale: BioScale.tissue,
      tagline: 'Rebuild the skin, surface to deep',
      rules: const [
        'Drag layers into depth order: surface on top, deep at bottom.',
        'Right depth links healthy; wrong order flags the boundary red.',
        'Tap a tile to read what its layer holds and does.',
        'Complete a section and the skin comes alive: +bonus.',
      ],
      howToWin: 'Place the most skin layers correctly before time runs out.',
      durationSeconds: 60,
      scoreUnit: 'layers',
      enabled: true,
      accent: const Color(0xFFFF8A65),
      icon: Icons.layers,
      humanMax: 900,
      starThresholds: const [300, 550, 800],
      builder: (context, session) => SkinLayersGame(session: session),
    ),
    MiniGameSpec(
      id: 'cell_type',
      name: 'Cell Type',
      scale: BioScale.cell,
      tagline: 'Read the structures — plant, animal, bacterial, or fungal?',
      rules: const [
        'A cell is drawn from its real structures — classify it.',
        'Tap PLANT / ANIMAL / BACTERIAL / FUNGAL.',
        'Faster correct answers score more.',
        'Chain correct answers to build a streak multiplier.',
      ],
      howToWin: 'Most cells correctly classified before time runs out wins.',
      durationSeconds: 60,
      scoreUnit: 'cells',
      enabled: true,
      accent: const Color(0xFF4CAF50),
      icon: Icons.biotech_rounded,
      humanMax: 2000,
      starThresholds: const [600, 1300, 2000],
      builder: (context, session) => CellTypeGame(session: session),
    ),
    MiniGameSpec(
      id: 'osmosis',
      name: 'Osmosis',
      scale: BioScale.cell,
      tagline: 'Balance the water — keep the cell from bursting or shriveling',
      rules: [
        'Water crosses the membrane toward the saltier side.',
        'Slide left to ADD WATER (cell swells), right to ADD SOLUTE (cell shrinks).',
        'Hold the cell in the green band: +6/sec; recover it after drifting out: +35.',
        'Too hypotonic bursts it (lysis); too hypertonic shrivels it (crenation).',
      ],
      howToWin: 'Most points — keep the cell healthy — when time runs out wins.',
      durationSeconds: 60,
      scoreUnit: 'pts',
      enabled: true,
      accent: const Color(0xFF26C6DA),
      icon: Icons.water_drop,
      humanMax: 700,
      starThresholds: const [220, 450, 700],
      builder: (context, session) => OsmosisGame(session: session),
    ),
    MiniGameSpec(
      id: 'powerhouse',
      name: 'Powerhouse',
      scale: BioScale.organelle,
      tagline: 'Run a mitochondrion — turn glucose + oxygen into ATP',
      rules: const [
        'Tap FEED GLUCOSE and FEED OXYGEN to fill the tanks.',
        'Tap the mitochondrion to drive the respiration cycle.',
        'Full oxygen = aerobic = +36 ATP; no oxygen = +2 ATP.',
        'Overfeeding a full tank stalls production.',
      ],
      howToWin: 'Most ATP produced when time runs out wins.',
      durationSeconds: 60,
      scoreUnit: 'ATP',
      enabled: true,
      accent: const Color(0xFFE16416),
      icon: Icons.bolt,
      humanMax: 800,
      starThresholds: const [250, 450, 650],
      builder: (context, session) => PowerhouseGame(session: session),
    ),
    MiniGameSpec(
      id: 'tissue_type',
      name: 'Tissue Type',
      scale: BioScale.tissue,
      tagline: 'Read the slide — name the tissue',
      rules: [
        'A stained tissue slide appears: tap its type.',
        'Read shape, not colour: sheet / scatter / fibre / star.',
        'Faster correct answers score more.',
        'Every 3 in a row adds a streak multiplier.',
      ],
      howToWin: 'Most points when the timer runs out wins.',
      durationSeconds: 60,
      scoreUnit: 'points',
      enabled: true,
      accent: const Color(0xFFD81B60),
      icon: Icons.biotech_rounded,
      humanMax: 4200,
      starThresholds: const [1400, 2800, 4000],
      builder: (context, session) => TissueTypeGame(session: session),
    ),
    MiniGameSpec(
      id: 'heartbeat',
      name: 'Heartbeat',
      scale: BioScale.organ,
      tagline: 'Pump blood through the heart, on the beat',
      rules: const [
        'Tap the next chamber in order: Body→RA→RV→Lungs→LA→LV→Body.',
        'Tap on the beat — when the ring snaps shut: clean pump.',
        'Blue blood turns red at the lungs (oxygenated).',
        'Wrong order or mistimed = stall, streak resets. Full cycle = +40.',
      ],
      howToWin: 'Most clean pumps when time runs out wins.',
      durationSeconds: 60,
      scoreUnit: 'pumps',
      enabled: true,
      accent: const Color(0xFFE5484D),
      icon: Icons.favorite,
      humanMax: 1600,
      starThresholds: const [350, 800, 1400],
      builder: (context, session) => HeartbeatGame(session: session),
    ),
    MiniGameSpec(
      id: 'transcribe',
      name: 'Transcribe',
      scale: BioScale.cell,
      tagline: 'Read the DNA, build the mRNA',
      rules: const [
        'Tap the mRNA base that pairs the active DNA base.',
        'A→U · T→A · C→G · G→C (mRNA uses U, never T).',
        'Beat the timing bar — wrong or late breaks the strand.',
        'Every 3 clean bases = a codon → amino acid.',
      ],
      howToWin: 'Most bases transcribed when time runs out wins.',
      durationSeconds: 60,
      scoreUnit: 'bases',
      enabled: true,
      accent: const Color(0xFF18C99A),
      icon: Icons.biotech,
      humanMax: 800,
      starThresholds: const [250, 500, 750],
      builder: (context, session) => TranscribeGame(session: session),
    ),
    MiniGameSpec(
      id: 'nephron',
      name: 'Nephron',
      scale: BioScale.organ,
      tagline: 'Run the kidney\'s filter — reabsorb the good, let the waste flow',
      rules: [
        'Blood pours down the tubule. Sort each molecule before it exits.',
        'Flick a molecule LEFT to reabsorb it into the BLOOD.',
        'Flick it RIGHT (or let it fall) to send it out as URINE.',
        'Reabsorb nutrients; let waste pass. Mistakes drain BLOOD PURITY.',
      ],
      howToWin: 'Highest score when time runs out — reabsorb nutrients, excrete toxins.',
      durationSeconds: 60,
      scoreUnit: 'molecules',
      enabled: true,
      accent: const Color(0xFFC65A6E),
      icon: Icons.filter_alt,
      humanMax: 1400,
      starThresholds: const [400, 850, 1400],
      builder: (context, session) => NephronGame(session: session),
    ),
    MiniGameSpec(
      id: 'body_map',
      name: 'Body Map',
      scale: BioScale.organ,
      tagline: 'Drag each organ to where it lives in the body',
      rules: [
        'An organ flies up from the tray — drag it onto the body.',
        'Drop it on its real spot to snap it in; a wrong spot bounces back.',
        'Place fast and dead-center for speed and accuracy bonuses.',
        'Chain placements for a streak; each cleared body adds more organs.',
      ],
      howToWin: 'Most points when time runs out wins.',
      durationSeconds: 60,
      scoreUnit: 'points',
      enabled: true,
      accent: const Color(0xFFB23A48),
      icon: Icons.accessibility_new,
      humanMax: 1800,
      starThresholds: const [500, 1000, 1600],
      builder: (context, session) => BodyMapGame(session: session),
    ),
    MiniGameSpec(
      id: 'circulate',
      name: 'Circulate',
      scale: BioScale.organSystem,
      tagline: 'Route oxygen through the body, recharge at the lungs',
      rules: const [
        'Tap a low organ: route red blood, deliver O₂.',
        'Tap the lungs: recharge the blue blood.',
        'Rescue near-empty organs for more points.',
        "Don't let an organ starve to zero.",
      ],
      howToWin: 'Most O₂ deliveries when time runs out wins.',
      durationSeconds: 50,
      scoreUnit: 'deliveries',
      enabled: true,
      accent: const Color(0xFFE5384B),
      icon: Icons.favorite,
      humanMax: 650,
      starThresholds: const [200, 400, 600],
      builder: (context, session) => CirculateGame(session: session),
    ),
    MiniGameSpec(
      id: 'half_life',
      name: 'Half-Life',
      scale: BioScale.atoms,
      tagline: 'Tap MEASURE when half the glow is gone',
      rules: [
        'Atoms glow, then randomly decay to stable.',
        'Each round names a half-life and a target %.',
        'Tap MEASURE when that fraction still glows.',
        'Closer to the true moment = more points.',
      ],
      howToWin: 'Most accurate measurements when time runs out wins.',
      durationSeconds: 50,
      scoreUnit: 'accuracy',
      enabled: true,
      accent: const Color(0xFF7DFB5A),
      icon: Icons.timelapse,
      humanMax: 800,
      starThresholds: const [320, 560, 760],
      builder: (context, session) => HalfLifeGame(session: session),
    ),
    MiniGameSpec(
      id: 'digest',
      name: 'Digest',
      scale: BioScale.organSystem,
      tagline: 'Route the food down the tract — chew, churn, absorb',
      rules: [
        'Wait for a morsel to glow gold, then tap its stage action.',
        'CHEW · SWALLOW · CHURN · ABSORB NUTRIENTS · ABSORB WATER.',
        'Nutrients (small intestine) & water (large intestine) score most.',
        'One bolus per stage — clear the FRONT first or food backs up.',
      ],
      howToWin: 'Most food processed when time runs out wins.',
      durationSeconds: 55,
      scoreUnit: 'processed',
      enabled: true,
      accent: const Color(0xFFE0734B),
      icon: Icons.lunch_dining,
      humanMax: 700,
      starThresholds: const [240, 440, 640],
      builder: (context, session) => DigestGame(session: session),
    ),
    MiniGameSpec(
      id: 'homeostasis',
      name: 'Homeostasis',
      scale: BioScale.organism,
      tagline: 'Keep every system in its safe band at once',
      rules: [
        'Each gauge drifts — watch the needle leave the green band.',
        'Tap ▼ to lower or ▲ to raise the matching response.',
        'Too high → SWEAT / PEE / INSULIN · too low → SHIVER / DRINK / GLUCAGON.',
        'Pull a system back in-band: +25 · all in-band at once: balance bonus.',
      ],
      howToWin: 'Most balance when time runs out — score for every second all systems stay in-band.',
      durationSeconds: 50,
      scoreUnit: 'balance',
      enabled: true,
      accent: const Color(0xFF4DD0E1),
      icon: Icons.thermostat,
      humanMax: 600,
      starThresholds: const [200, 380, 540],
      builder: (context, session) => HomeostasisGame(session: session),
    ),
    MiniGameSpec(
      id: 'phase_change',
      name: 'Phase Change',
      scale: BioScale.molecular,
      tagline: 'Heat and cool matter to hold a state',
      rules: const [
        'Hold HEAT to add energy, COOL to remove it.',
        'Reach the target state: SOLID / LIQUID / GAS.',
        'Hold it until the bar fills to score.',
        'Push through the latent-heat plateau to change state.',
      ],
      howToWin: 'Hold the most target states before time runs out.',
      durationSeconds: 52,
      scoreUnit: 'states',
      enabled: true,
      accent: const Color(0xFFFF7043),
      icon: Icons.thermostat,
      humanMax: 12,
      starThresholds: const [4, 8, 12],
      builder: (context, session) => PhaseChangeGame(session: session),
    ),
    MiniGameSpec(
      id: 'bond_lab',
      name: 'Bond Lab',
      scale: BioScale.molecular,
      tagline: 'Pick the bond: ionic, covalent, or metallic',
      rules: [
        'Two atoms appear with their electronegativity and metal/nonmetal tag.',
        'Metal+nonmetal = IONIC, two nonmetals = COVALENT, two metals = METALLIC.',
        'Right bond forms the compound and a streak bonus. Wrong bond fizzles.',
      ],
      howToWin: 'Most compounds bonded when time runs out wins.',
      durationSeconds: 50,
      scoreUnit: 'compounds',
      enabled: true,
      accent: const Color(0xFF7E57C2),
      icon: Icons.hub,
      humanMax: 360,
      starThresholds: const [110, 230, 350],
      builder: (context, session) => BondLabGame(session: session),
    ),
    MiniGameSpec(
      id: 'reflex',
      name: 'Reflex',
      scale: BioScale.organSystem,
      tagline: 'Fire before the damage lands',
      rules: const [
        'Wait — tapping early is a false start: −15.',
        'Tap the instant the receptor flashes.',
        'Ignore the brain decoy — only the receptor is real.',
        'Faster reaction = more points; chain hits for a streak bonus.',
      ],
      howToWin: 'Most reaction points when time runs out wins.',
      durationSeconds: 50,
      scoreUnit: 'reaction',
      enabled: true,
      accent: const Color(0xFFC6FF00),
      icon: Icons.bolt,
      humanMax: 1700,
      starThresholds: const [500, 1000, 1500],
      builder: (context, session) => ReflexGame(session: session),
    ),
    MiniGameSpec(
      id: 'life_cycle',
      name: 'Life Cycle',
      scale: BioScale.organism,
      tagline: 'Spin the wheel of life — call the next stage',
      rules: const [
        'Read the current stage on the turning wheel.',
        'Tap the correct NEXT stage: +points.',
        'Faster answers score more; 3 in a row = ×multiplier.',
        'Miss reveals the right next stage (no penalty).',
      ],
      howToWin: 'Most correct life-cycle transitions before time runs out wins.',
      durationSeconds: 50,
      scoreUnit: 'transitions',
      enabled: true,
      accent: const Color(0xFFE16416),
      icon: Icons.cyclone,
      humanMax: 3500,
      starThresholds: const [1200, 2400, 3600],
      builder: (context, session) => LifeCycleGame(session: session),
    ),
    MiniGameSpec(
      id: 'food_web',
      name: 'Food Web',
      scale: BioScale.ecosystem,
      tagline: 'Wire energy up the pyramid',
      rules: const [
        'Drag prey → what eats it: correct link lights up.',
        'Energy flows UP only — backwards or level-skips fizzle.',
        'Decomposers take energy from anything: bonus.',
        'Wire every link to complete the web for a bonus.',
      ],
      howToWin: 'Most correct energy links and completed webs when time runs out wins.',
      durationSeconds: 50,
      scoreUnit: 'links',
      enabled: true,
      accent: const Color(0xFF7CB342),
      icon: Icons.account_tree,
      humanMax: 1000,
      starThresholds: const [300, 600, 900],
      builder: (context, session) => FoodWebGame(session: session),
    ),
    MiniGameSpec(
      id: 'electron_shells',
      name: 'Electron Shells',
      scale: BioScale.atoms,
      tagline: 'Seat electrons shell by shell into a stable atom',
      rules: [
        'Tap an electron: drops into the selected shell (+6).',
        'Fill shells inside-out — K=2, L=8, M=8.',
        'Complete an octet/duet: +12. Stabilize the atom: +40.',
        'Overfill or wrong order: unstable, −7.',
      ],
      howToWin: 'Most atoms stabilized when time runs out wins.',
      durationSeconds: 50,
      scoreUnit: 'atoms',
      enabled: true,
      accent: const Color(0xFF4F9DFF),
      icon: Icons.track_changes,
      humanMax: 1200,
      starThresholds: const [400, 750, 1100],
      builder: (context, session) => ElectronShellsGame(session: session),
    ),
    MiniGameSpec(
      id: 'isotopes',
      name: 'Isotopes',
      scale: BioScale.atoms,
      tagline: 'Dial protons and neutrons to build the nuclide',
      rules: [
        '+/- PROTONS sets the element (atomic number Z).',
        '+/- NEUTRONS sets the isotope; mass A = protons + neutrons.',
        'Match both the ELEMENT and ISOTOPE pills, then LOCK IT IN.',
        'Lock fast and keep a streak for bonus points.',
      ],
      howToWin: 'Most nuclides built when time runs out wins.',
      durationSeconds: 50,
      scoreUnit: 'nuclides',
      enabled: true,
      accent: const Color(0xFF4DD0E1),
      icon: Icons.scatter_plot,
      humanMax: 350,
      starThresholds: const [130, 240, 330],
      builder: (context, session) => IsotopesGame(session: session),
    ),
    MiniGameSpec(
      id: 'forage',
      name: 'Forage',
      scale: BioScale.organism,
      tagline: 'Eat to live — but every move spends what you eat',
      rules: const [
        'Drag to steer your animal — moving spends energy.',
        'Eat food to refill energy (and bank it as score).',
        'A meal that gives more than it cost to reach is EFFICIENT — chain them.',
        'Rest between bites; dodge predators. Run empty and you starve.',
      ],
      howToWin: 'Bank the most energy when time runs out wins.',
      durationSeconds: 50,
      scoreUnit: 'energy',
      enabled: true,
      accent: const Color(0xFF7CC576),
      icon: Icons.pets,
      humanMax: 600,
      starThresholds: const [200, 400, 600],
      builder: (context, session) => ForageGame(session: session),
    ),
    MiniGameSpec(
      id: 'nutrient_cycle',
      name: 'Nutrient Cycle',
      scale: BioScale.ecosystem,
      tagline: 'Route the atom round the loop — matter cycles, energy flows',
      rules: const [
        'Tap the next reservoir in the cycle: +1.',
        'Only named processes are valid moves.',
        'Close a full loop: +5.',
        'Keep moving — the FLOW meter drains.',
      ],
      howToWin: 'Cycle the most matter before time runs out.',
      durationSeconds: 50,
      scoreUnit: 'transfers',
      enabled: true,
      accent: const Color(0xFF6FBF73),
      icon: Icons.recycling,
      humanMax: 70,
      starThresholds: const [25, 45, 65],
      builder: (context, session) => NutrientCycleGame(session: session),
    ),
    MiniGameSpec(
      id: 'ph_balance',
      name: 'pH Balance',
      scale: BioScale.molecular,
      tagline: 'Titrate the beaker to the target pH — and hold it steady',
      rules: [
        'Tap ACID to lower pH, BASE to raise it.',
        'Land in the target band and hold to lock it.',
        'Near pH 7 the curve is steep — drops swing hard.',
      ],
      howToWin: 'Hit the most targets before time runs out.',
      durationSeconds: 50,
      scoreUnit: 'balance',
      enabled: true,
      accent: const Color(0xFF3DDC97),
      icon: Icons.science,
      humanMax: 900,
      starThresholds: const [300, 550, 800],
      builder: (context, session) => PhBalanceGame(session: session),
    ),
    MiniGameSpec(
      id: 'predator_prey',
      name: 'Predator & Prey',
      scale: BioScale.ecosystem,
      tagline: 'Keep the boom-bust cycle alive — don\'t let either species crash to zero',
      rules: const [
        'Hares (prey) breed; lynx (predators) starve without them.',
        'Watch the two-line graph swing: prey boom, predators boom, prey crash…',
        'Release or cull each species; PROTECT a patch for a refuge.',
        'Keep BOTH (then the hawks too) off zero and near balance.',
      ],
      howToWin: 'Most TIME with both species alive and in balance when time runs out wins.',
      durationSeconds: 50,
      scoreUnit: 'balance',
      enabled: true,
      accent: const Color(0xFF6FCF6B),
      icon: Icons.pets,
      humanMax: 480,
      starThresholds: const [150, 300, 440],
      builder: (context, session) => PredatorPreyGame(session: session),
    ),
    MiniGameSpec(
      id: 'quantum_foam',
      name: 'Quantum Foam',
      scale: BioScale.nothings,
      tagline: 'Harvest borrowed energy before it annihilates',
      rules: [
        'Tap a flickering pair while alive: harvest its energy.',
        'Shorter-lived pairs are worth MORE — but vanish faster.',
        'Let pairs annihilate untouched: free, no cost.',
        'Don\'t tap a steady gold REAL particle: −20.',
      ],
      howToWin: 'Most energy harvested when time runs out wins.',
      durationSeconds: 50,
      scoreUnit: 'eV',
      enabled: true,
      accent: const Color(0xFF9B6DFF),
      icon: Icons.blur_on,
      humanMax: 520,
      starThresholds: const [140, 300, 460],
      builder: (context, session) => QuantumFoamGame(session: session),
    ),
    MiniGameSpec(
      id: 'bubbles',
      name: 'Bubbles',
      scale: BioScale.multiverseAll,
      tagline: 'Nucleate bubble universes in the inflating void',
      rules: [
        'Tap the void: nucleate a bubble universe.',
        'Let it inflate gold, then tap to harvest.',
        'Keep them apart — collisions spoil both.',
      ],
      howToWin: 'Most universes harvested when time runs out wins.',
      durationSeconds: 50,
      scoreUnit: 'universes',
      enabled: true,
      accent: const Color(0xFF8B5CF6),
      icon: Icons.bubble_chart,
      humanMax: 420,
      starThresholds: const [150, 280, 400],
      builder: (context, session) => BubblesGame(session: session),
    ),
    MiniGameSpec(
      id: 'the_wait',
      name: 'The Wait',
      scale: BioScale.nothings,
      tagline: 'Feel the seconds in the dark',
      rules: const [
        'Read the target: WAIT N seconds.',
        'Screen goes black — no clock, no cues.',
        'Tap when you feel N seconds have passed.',
        'Closer to N = more points; no tap = 0.',
      ],
      howToWin: 'Bank the most points across 6 timing rounds.',
      durationSeconds: 60,
      scoreUnit: 'points',
      enabled: true,
      accent: const Color(0xFF8C7AE6),
      icon: Icons.hourglass_empty,
      humanMax: 480,
      starThresholds: const [200, 340, 460],
      builder: (context, session) => TheWaitGame(session: session),
    ),
    MiniGameSpec(
      id: 'superposition',
      name: 'Superposition',
      scale: BioScale.multiverseAll,
      tagline: 'Collapse the wavefunction at the perfect moment',
      rules: [
        'A qubit oscillates between |↑⟩ and |↓⟩ — odds sweep 0–100%.',
        'The glowing pole is your target state.',
        'Tap to MEASURE: collapse near 100% to land it.',
        'Measure at 50/50 and it is a coin-flip.',
      ],
      howToWin: 'Most favorable collapses when time runs out wins.',
      durationSeconds: 50,
      scoreUnit: 'collapses',
      enabled: true,
      accent: const Color(0xFF7272AB),
      icon: Icons.blur_on,
      humanMax: 3000,
      starThresholds: const [900, 1800, 2800],
      builder: (context, session) => SuperpositionGame(session: session),
    ),
    MiniGameSpec(
      id: 'cosmic_timeline',
      name: 'Cosmic Timeline',
      scale: BioScale.universeAll,
      tagline: 'Put 13.8 billion years in order',
      rules: const [
        'Drag epoch cards into chronological slots: earliest ➜ latest.',
        'Right slot: link flows teal and reveals its "when".',
        'Wrong order: the arrow into it snaps red — fix it.',
        'Tap a placed card to pull it back; tap a tray card to read its fact.',
      ],
      howToWin: 'Most points when time runs out — order epochs and lock whole timelines.',
      durationSeconds: 60,
      scoreUnit: 'epochs',
      enabled: true,
      accent: const Color(0xFF7C4DFF),
      icon: Icons.timeline,
      humanMax: 700,
      starThresholds: const [200, 400, 650],
      builder: (context, session) => CosmicTimelineGame(session: session),
    ),
    MiniGameSpec(
      id: 'standard_model',
      name: 'Standard Model',
      scale: BioScale.particles,
      tagline: 'Sort every particle into its family',
      rules: [
        'Particles stream down — drag each into a bin.',
        'QUARKS · LEPTONS · BOSONS: match the family to score.',
        'Wrong bin fizzles; let one sink and you miss it.',
        'Tells (charge, colour, mass) fade as you climb.',
      ],
      howToWin: 'Most particles correctly sorted when time runs out wins.',
      durationSeconds: 50,
      scoreUnit: 'particles',
      enabled: true,
      accent: const Color(0xFF7C4DFF),
      icon: Icons.bubble_chart,
      humanMax: 800,
      starThresholds: const [250, 500, 750],
      builder: (context, session) => StandardModelGame(session: session),
    ),
    MiniGameSpec(
      id: 'converge',
      name: 'Converge',
      scale: BioScale.infinities,
      tagline: 'Judge an infinite sum: does it settle on a line, or run away?',
      rules: [
        'A series streams its terms; the running sum Sₙ climbs the chart.',
        'CONVERGE-OR-DIVERGE: tap whether the sum settles or grows forever.',
        'NAME-THE-LIMIT: for a convergent series, tap the value it approaches.',
        'Call it early for more points — speed bonus × streak multiplier.',
      ],
      howToWin: 'Highest score when the 55s clock ends.',
      durationSeconds: 55,
      scoreUnit: 'points',
      enabled: true,
      accent: const Color(0xFF4DD0E1),
      icon: Icons.all_inclusive,
      humanMax: 1600,
      starThresholds: const [450, 900, 1500],
      builder: (context, session) => ConvergeGame(session: session),
    ),
    MiniGameSpec(
      id: 'tzimtzum',
      name: 'Tzimtzum',
      scale: BioScale.nothings,
      tagline: 'Withdraw at a steady rate to make space',
      rules: [
        'Two fingers: PINCH to contract, STRETCH to expand.',
        'Hold a STEADY, constant rate for the full duration.',
        'Too fast = collapse · too slow = few points.',
        'Keep the marker in the ideal band.',
      ],
      howToWin: 'Most points when time runs out — steady, complete holds win.',
      durationSeconds: 45,
      scoreUnit: 'space',
      enabled: true,
      accent: const Color(0xFF8E7BEF),
      icon: Icons.pinch,
      humanMax: 1200,
      starThresholds: const [350, 700, 1100],
      builder: (context, session) => TzimtzumGame(session: session),
    ),
    MiniGameSpec(
      id: 'decay_chain',
      name: 'Decay Chain',
      scale: BioScale.particles,
      tagline: 'Catch the decay products before they escape the detector',
      rules: const [
        'Tap real decay products: +10.',
        'Finish a decay clean (no escapes): +25 & streak.',
        'Tap the impostor particle: −12.',
        'Let a real product escape: −5.',
      ],
      howToWin: 'Most particles caught when the reactor cools wins.',
      durationSeconds: 50,
      scoreUnit: 'particles',
      enabled: true,
      accent: const Color(0xFF64DD17),
      icon: Icons.scatter_plot,
      humanMax: 950,
      starThresholds: const [300, 600, 900],
      builder: (context, session) => DecayChainGame(session: session),
    ),
    MiniGameSpec(
      id: 'branch',
      name: 'Branch',
      scale: BioScale.multiverseAll,
      tagline: 'Every choice splits the world — ride the heavier branch',
      rules: const [
        'Tap TOP half to ride the upper branch, BOTTOM half for the lower.',
        'Each fork shows two amplitudes — the heavier branch scores more.',
        'Pick the heavier branch for a CLEAN streak bonus.',
        'You can\'t prune — the branch you skip keeps splitting on its own.',
      ],
      howToWin: 'Most amplitude gathered when time runs out wins.',
      durationSeconds: 50,
      scoreUnit: 'amplitude',
      enabled: true,
      accent: const Color(0xFF54D1FF),
      icon: Icons.account_tree,
      humanMax: 4200,
      starThresholds: const [1400, 2800, 4200],
      builder: (context, session) => BranchGame(session: session),
    ),
    MiniGameSpec(
      id: 'pattern_lock',
      name: 'Pattern Lock',
      scale: BioScale.somethings,
      tagline: 'Read the rule. Lock in what comes next.',
      rules: [
        'A pattern appears — tap what comes NEXT.',
        'Faster correct picks score more.',
        '3 in a row = streak multiplier.',
        'Late game: tap the value that BREAKS the rule.',
      ],
      howToWin: 'Most points when time runs out wins.',
      durationSeconds: 50,
      scoreUnit: 'patterns',
      enabled: true,
      accent: const Color(0xFF9575CD),
      icon: Icons.lock_outline_rounded,
      humanMax: 2800,
      starThresholds: const [700, 1500, 2500],
      builder: (context, session) => PatternLockGame(session: session),
    ),
    MiniGameSpec(
      id: 'constants',
      name: 'Constants',
      scale: BioScale.universeAll,
      tagline: 'Tune reality into the habitable band',
      rules: [
        'Drag each dial into its green band.',
        'Keep ALL dials in band: universe stays life-permitting.',
        'Stabilise red-flashed shocks for +60.',
        'Bands narrow and drift speeds up — more dials unlock.',
      ],
      howToWin: 'Most time life-permitting (all dials in band) plus shocks stabilised wins.',
      durationSeconds: 55,
      scoreUnit: 'stability',
      enabled: true,
      accent: const Color(0xFF8B7CF6),
      icon: Icons.tune,
      humanMax: 1000,
      starThresholds: const [350, 650, 950],
      builder: (context, session) => ConstantsGame(session: session),
    ),
    MiniGameSpec(
      id: 'hilberts_hotel',
      name: "Hilbert's Hotel",
      scale: BioScale.infinities,
      tagline: 'A full ∞ hotel — yet always room for more',
      rules: const [
        'The hotel is FULL — every room 1, 2, 3, … has a guest.',
        'Read the arrival: 1 guest · a bus of ℵ₀ · infinitely many buses.',
        'Tap the rule that makes room: n→n+1, n→2n, or prime powers.',
        'Wrong rules double-book, evict, or hit a dead end — and score 0.',
      ],
      howToWin: 'Most correct accommodations when time runs out wins.',
      durationSeconds: 50,
      scoreUnit: 'check-ins',
      enabled: true,
      accent: const Color(0xFFE1C916),
      icon: Icons.hotel_rounded,
      humanMax: 2600,
      starThresholds: const [700, 1400, 2100],
      builder: (context, session) => HilbertsHotelGame(session: session),
    ),
    MiniGameSpec(
      id: 'powers_of_ten',
      name: 'Powers of Ten',
      scale: BioScale.universeAll,
      tagline: 'Place each thing on the cosmic size ladder',
      rules: [
        'Drag the marker up/down the ladder.',
        'Release to drop it at the right power of ten.',
        'Closer to the true magnitude = more points.',
        'Size → mass → time ladders rotate in as you climb.',
      ],
      howToWin: 'Most precision points when time runs out wins.',
      durationSeconds: 50,
      scoreUnit: 'precision',
      enabled: true,
      accent: const Color(0xFF22D3EE),
      icon: Icons.zoom_out_map,
      humanMax: 1500,
      starThresholds: const [500, 950, 1400],
      builder: (context, session) => PowersOfTenGame(session: session),
    ),
  ];

  static final List<MiniGameSpec> enabledSpecs =
      specs.where((s) => s.enabled).toList();

  static MiniGameSpec? byId(String id) {
    for (final s in specs) {
      if (s.id == id) return s;
    }
    return null;
  }

  /// The party-ready spec for a scale, or null if that scale only has a
  /// legacy explore game. (Returns the FIRST enabled spec — use
  /// [gamesForScale] when you need every game on a scale.)
  static MiniGameSpec? forScale(BioScale scale) {
    for (final s in specs) {
      if (s.scale == scale && s.enabled) return s;
    }
    return null;
  }

  /// Every enabled game on a scale, in registry order. A scale can have more
  /// than one (e.g. particles → Collider + Accelerator); Explore shows a
  /// picker when this returns more than one.
  static List<MiniGameSpec> gamesForScale(BioScale scale) =>
      specs.where((s) => s.scale == scale && s.enabled).toList();
}
