// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTpLzLsG0VS6i2_47fhzgkgypZBNNSkf4',
    appId: '1:1083610814923:web:36b8e34a831b421a15be4e',
    messagingSenderId: '1083610814923',
    projectId: 'hot-potato-games',
    authDomain: 'hot-potato-games.firebaseapp.com',
    databaseURL: 'https://hot-potato-games-default-rtdb.firebaseio.com',
    storageBucket: 'hot-potato-games.firebasestorage.app',
    measurementId: 'G-GN9W12TYJF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn59E9dD_8a2TFiYzrO6MDpFJDFVRDwqs',
    appId: '1:1083610814923:android:a856d2e67a98197115be4e',
    messagingSenderId: '1083610814923',
    projectId: 'hot-potato-games',
    databaseURL: 'https://hot-potato-games-default-rtdb.firebaseio.com',
    storageBucket: 'hot-potato-games.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKCRxEcfy78ejwiRHRibtWX_HlfggkqRg',
    appId: '1:1083610814923:ios:6aa265e263773ffc15be4e',
    messagingSenderId: '1083610814923',
    projectId: 'hot-potato-games',
    databaseURL: 'https://hot-potato-games-default-rtdb.firebaseio.com',
    storageBucket: 'hot-potato-games.firebasestorage.app',
    iosClientId: '1083610814923-6tgeule3ad4lbsvldoi5tblvu1a9jfk8.apps.googleusercontent.com',
    iosBundleId: 'com.bjo.cell',
  );
}
