import 'package:cell_mobile/models/bio_entity.dart';
import 'package:cell_mobile/models/lesson_section.dart';

const planetsEntities = <BioEntity>[
  BioEntity(
    id: 'planets_earth',
    scale: BioScale.planets,
    position: 0,
    name: 'Earth',
    title: 'The Blue Marble',
    shortDescription: 'The only known world harboring life — a thin shell of atmosphere wrapped around a molten iron core, orbiting an unremarkable star in an unremarkable galaxy.',
    longDescription:
        'Earth is a ~4.54-billion-year-old rocky planet with a radius of ~6,371 km, orbiting the Sun at an average distance of ~149.6 million km — close enough that liquid water can persist on its surface, far enough that it does not boil away. Several overlapping accidents make the planet extraordinary: a molten iron core generates a magnetic field that deflects the solar wind, plate tectonics recycle carbon and buffer climate over geological time, and an unusually large Moon steadies the axial tilt against chaotic wobble.\n\n'
        'Read biologically, Earth is a single cell writ enormous — a bounded system with an energy source (the Sun), a membrane (the atmosphere), internal recycling (the geological and hydrological cycles), and a swarm of self-replicating chemistry (life). Everything from the earlier scales of this app — molecule, organelle, cell, ecosystem — lives inside this one fragile envelope, a biosphere proportionally thinner than the skin on an apple.',
    relatedIds: ['planets_mars', 'planets_exoplanets', 'global_climate', 'solar_earth_system'],
    sections: [
      LessonSection.fact(
        title: 'The habitable film',
        body: 'The entire biosphere — deepest ocean vent to highest airborne microbe — fits inside a shell roughly ~20 km thick on a planet ~12,700 km across. Scale it to an apple and life is thinner than the skin.',
      ),
      LessonSection.table(
        title: 'Earth by the numbers',
        headers: ['Property', 'Value'],
        rows: [
          ['Radius', '~6,371 km'],
          ['Age', '~4.54 billion years'],
          ['Distance from Sun', '~149.6 million km (1 AU)'],
          ['Day (rotation)', '~24 hours'],
          ['Year (orbit)', '~365.25 days'],
          ['Surface water', '~71% of surface'],
          ['Axial tilt', '~23.4°'],
        ],
      ),
      LessonSection.table(
        title: 'The four life-support systems',
        headers: ['System', 'What it does', 'Failure mode'],
        rows: [
          ['Magnetic field', 'Deflects solar wind', 'Atmosphere stripped away'],
          ['Plate tectonics', 'Recycles carbon, buffers climate', 'Runaway warming or freezing'],
          ['Large Moon', 'Stabilizes axial tilt', 'Chaotic seasons'],
          ['Atmosphere', 'Traps heat, blocks UV', 'Surface too cold or irradiated'],
        ],
      ),
      LessonSection.thinkReveal(
        title: 'The tilt question',
        question: 'Why would losing the Moon threaten life on land, even though the Moon supplies no heat and no air?',
        answer: 'The Moon is massive enough to gravitationally anchor Earth\'s ~23.4° axial tilt. Without it, gravitational tugs from the Sun and planets could let the tilt swing chaotically over millions of years — sometimes near 0°, sometimes far over. That would swap mild, predictable seasons for violent climate lurches that most complex ecosystems could not track. The Moon\'s contribution is stability, not warmth.',
      ),
      LessonSection.thinkReveal(
        title: 'Goldilocks, but not only distance',
        question: 'Venus sits closer to the Sun and Mars farther, yet both are dead while Earth thrives. What breaks if you assume "right distance" is the whole story?',
        answer: 'Distance sets the starting temperature, but the outcome is decided by feedbacks. Venus\'s runaway greenhouse cooked its oceans away; Mars lost its magnetic field and let the solar wind strip its air. Earth stays livable because the carbon cycle (via plate tectonics) and the magnetic field actively regulate the system. Habitability is a maintained balance, not a fixed address.',
      ),
      LessonSection.paragraph(
        title: 'The dynamo underground',
        body: 'The magnetic shield is generated by convection in the liquid iron outer core — churning metal acting as a self-sustaining dynamo. It is invisible, it costs the planet nothing you can see, and it is the single line of defense keeping the atmosphere from being scoured into space. Every organism on the surface owes its air to the weather in a metal ocean thousands of kilometers below.',
      ),
    ],
  ),
  BioEntity(
    id: 'planets_mars',
    scale: BioScale.planets,
    position: 1,
    name: 'Mars',
    title: 'The Red Question',
    shortDescription: 'A cold, dry world that may have once been warm and wet — Mars is the mirror that shows us what Earth could become, and perhaps what it once was.',
    longDescription:
        'Mars orbits ~227.9 million km from the Sun beneath a thin CO2 atmosphere — less than ~1% of Earth\'s surface pressure — with no global magnetic field and an average surface temperature near -60 °C. By every current biological measure it is a dead world. Yet its geology tells an older story: river channels, deltas, and clay and sulfate minerals that only form in liquid water, all pointing to sustained warmth and wetness ~3.5–4 billion years ago.\n\n'
        'Mars is also a cautionary tale about fragility. It lost its magnetic field roughly ~4 billion years ago; the unshielded solar wind then eroded its atmosphere, pressure dropped, surface water became impossible, and the planet froze. Earth escaped that fate only because its liquid iron core still runs. Set side by side, the two worlds show just how narrow the conditions for a living surface really are.',
    relatedIds: ['planets_earth', 'planets_exoplanets', 'solar_habitable_zones'],
    sections: [
      LessonSection.fact(
        title: 'A whole atmosphere, gone',
        body: 'Mars\'s surface pressure is under ~1% of Earth\'s. When the magnetic field died ~4 billion years ago, the solar wind stripped most of its air into space — the same shield failure Earth\'s core prevents every second.',
      ),
      LessonSection.table(
        title: 'Mars vs. Earth',
        headers: ['Property', 'Mars', 'Earth'],
        rows: [
          ['Distance from Sun', '~227.9 million km', '~149.6 million km'],
          ['Surface pressure', '<1% of Earth\'s', '1 atm'],
          ['Mean surface temp', '~-60 °C', '~15 °C'],
          ['Global magnetic field', 'None (lost ~4 Gya)', 'Active'],
          ['Atmosphere', 'Mostly CO2, thin', 'N2/O2, thick'],
          ['Surface liquid water', 'None (ice + traces)', 'Abundant'],
        ],
      ),
      LessonSection.table(
        title: 'Evidence of a wet past',
        headers: ['Clue', 'What it implies'],
        rows: [
          ['Branching river channels', 'Flowing surface water'],
          ['Delta and lakebed deposits', 'Standing water over long spans'],
          ['Clay minerals', 'Prolonged rock-water contact'],
          ['Sulfate and salt beds', 'Evaporating bodies of water'],
        ],
      ),
      LessonSection.thinkReveal(
        title: 'The most consequential null result',
        question: 'Suppose Mars was warm and wet for hundreds of millions of years and life still never appeared. Why would that "nothing" be one of the most important discoveries in biology?',
        answer: 'It would mean liquid water and energy are not sufficient for life — that the origin of life needs some extra, rarer ingredient. Two independent worlds with the right conditions and only one producing life would push the odds toward life being hard and Earth being lucky. A confirmed second genesis would argue the opposite: that life ignites readily wherever chemistry allows. Either way, the answer reframes how alone we are likely to be.',
      ),
      LessonSection.thinkReveal(
        title: 'Cause and effect on a dying world',
        question: 'Mars lost its magnetic field AND lost its water. Which came first, and why does the order matter?',
        answer: 'The magnetic field failed first. With the shield gone, the solar wind eroded the atmosphere; as pressure fell, liquid water could no longer stay stable and either froze or escaped as vapor. Water loss was the symptom, magnetic collapse the cause — which is exactly why Earth\'s still-molten core matters so much. The lesson is that a planet\'s interior decides the fate of its surface.',
      ),
      LessonSection.paragraph(
        title: 'The mirror',
        body: 'Mars is valuable precisely because it is so nearly Earth-like and yet dead. It is the control group in an experiment we could otherwise never run: same Sun, similar rock, comparable early conditions — different ending. Every mission that studies why Mars died is really asking how Earth stays alive.',
      ),
    ],
  ),
  BioEntity(
    id: 'planets_exoplanets',
    scale: BioScale.planets,
    position: 2,
    name: 'Exoplanets',
    title: 'Worlds Beyond Count',
    shortDescription: 'Over 5,000 confirmed and billions estimated in our galaxy alone — exoplanets have transformed the question of life from philosophical speculation to statistical inevitability.',
    longDescription:
        'Before 1992 we knew of exactly zero planets outside our solar system. The first confirmed exoplanets orbited a pulsar; the first around a Sun-like star, 51 Pegasi b, arrived in 1995. NASA\'s Kepler mission alone confirmed over ~2,600 worlds, and the running total now exceeds ~5,000 — with statistical extrapolation suggesting there are more planets than stars in the Milky Way, on the order of ~100 billion.\n\n'
        'Their variety defies the tidy picture our own system suggested: hot Jupiters skimming their stars in days, super-Earths with no local analog, rogue planets unbound to any star, tidally locked worlds with one face in eternal day. For biology the stakes are enormous — if even a small fraction of rocky planets in their star\'s habitable zone develop life, the galaxy could be dense with biospheres, which only sharpens the Fermi Paradox: if life is common, where is everybody?',
    relatedIds: ['planets_earth', 'planets_mars', 'solar_habitable_zones', 'galactic_milky_way'],
    sections: [
      LessonSection.fact(
        title: 'From zero to a galaxy full',
        body: 'In ~1991 the count of known worlds beyond our Sun was 0. Today it is over ~5,000 confirmed, and estimates put the Milky Way\'s true total near ~100 billion — more planets than stars.',
      ),
      LessonSection.table(
        title: 'A field born in one generation',
        headers: ['Year', 'Milestone'],
        rows: [
          ['1992', 'First confirmed exoplanets (orbiting a pulsar)'],
          ['1995', '51 Pegasi b — first around a Sun-like star'],
          ['2009+', 'Kepler launches, confirms ~2,600 worlds'],
          ['Today', 'Over ~5,000 confirmed; billions estimated'],
        ],
      ),
      LessonSection.table(
        title: 'A zoo of worlds',
        headers: ['Type', 'Defining trait'],
        rows: [
          ['Hot Jupiter', 'Gas giant orbiting its star in days'],
          ['Super-Earth', 'Rocky, larger than Earth; no local analog'],
          ['Rogue planet', 'Bound to no star; drifts interstellar space'],
          ['Tidally locked', 'One hemisphere in permanent day, one in night'],
          ['Circumbinary', 'Orbits two stars at once'],
        ],
      ),
      LessonSection.thinkReveal(
        title: 'Why the paradox got worse',
        question: 'Discovering billions of potentially habitable planets should make alien life feel more likely. So why do many scientists say it deepens the Fermi Paradox?',
        answer: 'Because the paradox is the gap between expectation and silence. More habitable real estate raises the expected number of civilizations — yet we still detect none. The louder the odds say "they should be out there," the more the silence demands an explanation: life is rarer than the planet count suggests, or intelligence is, or civilizations are short-lived, or we simply cannot yet hear them. Abundant worlds make the empty sky harder to explain, not easier.',
      ),
      LessonSection.thinkReveal(
        title: 'The universal-chemistry test',
        question: 'Why do exoplanets turn the molecular processes from this app\'s earliest scales into a testable hypothesis rather than an Earth-only story?',
        answer: 'Every rocky world in a habitable zone is an independent run of the same chemistry experiment under different conditions. If life\'s molecular machinery is a universal consequence of physics, it should recur across many of them; if it is a fluke, Earth stays a lonely exception. With billions of trials available, the question "is our biochemistry inevitable or unique?" stops being philosophy and becomes something future telescopes can actually probe by sniffing exoplanet atmospheres for biosignatures.',
      ),
      LessonSection.paragraph(
        title: 'The commonest world is one we lack',
        body: 'The single most abundant class of planet found so far — the super-Earth, bigger than Earth but smaller than Neptune — does not exist in our own solar system. That absence is a quiet warning: our neighborhood is not a representative sample, and intuitions built from eight local planets can mislead us about what "normal" looks like across the galaxy.',
      ),
    ],
  ),
];
