import 'package:cell_mobile/models/bio_entity.dart';

const planetsEntities = <BioEntity>[
  BioEntity(
    id: 'planets_earth',
    scale: BioScale.planets,
    position: 0,
    name: 'Earth',
    title: 'The Blue Marble',
    shortDescription: 'The only known world harboring life — a thin shell of atmosphere wrapped around a molten iron core, orbiting an unremarkable star in an unremarkable galaxy.',
    longDescription:
        'Earth is a 4.54-billion-year-old rocky planet with a radius of 6,371 km, positioned at an average distance of 149.6 million km from the Sun — a distance so precisely calibrated that liquid water can exist on its surface. This "habitable zone" placement is one of several coincidences that make Earth extraordinary: a strong magnetic field generated by its molten iron core shields the atmosphere from solar wind, plate tectonics recycle carbon and regulate climate over geological timescales, and a large moon stabilizes axial tilt to prevent chaotic climate oscillations.\n\n'
        'From the perspective of biology, Earth is a single cell writ large — a bounded system with an energy source (the Sun), a membrane (the atmosphere), internal recycling mechanisms (geological and hydrological cycles), and a staggering diversity of self-replicating chemical systems (life). The biosphere — the thin layer from deep ocean vents to the upper atmosphere where life exists — is proportionally thinner than the skin of an apple relative to the fruit.\n\n'
        'Every organism explored in the earlier scales of this app — every molecule, every organelle, every cell, every ecosystem — exists within this fragile envelope. The transition from the "global" scale to the "planetary" scale is the moment we step back far enough to see Earth not as our world but as a world — one of billions in our galaxy alone, most of which are lifeless rocks tumbling through the void.',
    relatedIds: ['planets_mars', 'planets_exoplanets', 'global_climate', 'solar_earth_system'],
  ),
  BioEntity(
    id: 'planets_mars',
    scale: BioScale.planets,
    position: 1,
    name: 'Mars',
    title: 'The Red Question',
    shortDescription: 'A cold, dry world that may have once been warm and wet — Mars is the mirror that shows us what Earth could become, and perhaps what it once was.',
    longDescription:
        'Mars is 227.9 million km from the Sun, with a thin CO2 atmosphere (less than 1% of Earth\'s surface pressure), no global magnetic field, and surface temperatures averaging -60 degrees C. It is, by any biological measure, a dead world. And yet the evidence of its past tells a different story: river channels carved into its surface, mineral deposits that only form in liquid water, and clay minerals that suggest sustained periods of warmth and wetness 3.5-4 billion years ago.\n\n'
        'The question of whether Mars ever harbored life is one of the most profound in science. If life arose independently on Mars — even microbial life — it would suggest that life is not a fluke but a natural consequence of chemistry given the right conditions. If Mars was warm and wet for hundreds of millions of years and life never appeared, it would suggest that the origin of life requires something more than just water and energy — something rare, perhaps unique to Earth.\n\n'
        'Mars also serves as a cautionary tale. It lost its magnetic field roughly 4 billion years ago, allowing solar wind to strip away its atmosphere. Without atmospheric pressure, liquid water became impossible. The planet dried, froze, and died. Earth\'s magnetic field — generated by convection currents in its liquid iron outer core — is the invisible shield that prevents the same fate. The comparison between the two planets underscores how precarious the conditions for life truly are.',
    relatedIds: ['planets_earth', 'planets_exoplanets', 'solar_habitable_zones'],
  ),
  BioEntity(
    id: 'planets_exoplanets',
    scale: BioScale.planets,
    position: 2,
    name: 'Exoplanets',
    title: 'Worlds Beyond Count',
    shortDescription: 'Over 5,000 confirmed and billions estimated in our galaxy alone — exoplanets have transformed the question of life from philosophical speculation to statistical inevitability.',
    longDescription:
        'Before 1992, we knew of exactly zero planets outside our solar system. The discovery of exoplanets — first around pulsars, then around sun-like stars beginning with 51 Pegasi b in 1995 — has been one of the most revolutionary developments in the history of astronomy. NASA\'s Kepler mission alone confirmed over 2,600 exoplanets, and statistical extrapolation suggests there are more planets than stars in our galaxy — at least 100 billion worlds in the Milky Way alone.\n\n'
        'The diversity of these worlds defies imagination. Hot Jupiters orbit their stars in days. Super-Earths with no solar system analog are the most common type. Rogue planets drift through interstellar space, gravitationally unbound to any star. Some orbit binary star systems; others are tidally locked, with one hemisphere in perpetual daylight and the other in eternal night. The "habitable zone" concept — the orbital region where liquid water could exist — has been identified around thousands of stars.\n\n'
        'The implications for biology are staggering. If even a tiny fraction of rocky planets in habitable zones develop life — and if life, once started, tends to complexify over billions of years — then the galaxy could be teeming with biospheres. The Fermi Paradox (if life is common, where is everyone?) becomes more pressing with every new exoplanet discovery. Each world is a potential experiment in chemistry, a test of whether the molecular processes explored in the earliest scales of this app are universal or unique.',
    relatedIds: ['planets_earth', 'planets_mars', 'solar_habitable_zones', 'galactic_milky_way'],
  ),
];
