import 'package:cell_mobile/models/bio_entity.dart';

const solarSystemsEntities = <BioEntity>[
  BioEntity(
    id: 'solar_earth_system',
    scale: BioScale.solarSystems,
    position: 0,
    name: 'Our Sun',
    title: 'The Local Star',
    shortDescription: 'A middle-aged G-type main-sequence star — 4.6 billion years old, halfway through its life, converting 600 million tons of hydrogen to helium every second.',
    longDescription:
        'The Sun is a ball of plasma 1.4 million km in diameter, containing 99.86% of the solar system\'s total mass. At its core, temperatures reach 15 million degrees C and pressures exceed 250 billion atmospheres, conditions sufficient to fuse hydrogen nuclei into helium at a rate of 3.8 x 10^26 watts. This energy — generated by the same nuclear physics explored at the particle and atomic scales of this app — radiates outward through 700,000 km of solar interior before reaching the photosphere and streaming into space as light.\n\n'
        'Eight minutes and twenty seconds later, a tiny fraction of that light strikes Earth. This solar energy drives virtually every biological process on the planet: photosynthesis captures it, food webs distribute it, and cellular respiration releases it. The entire through-line of life — from molecular chemistry to global ecosystems — is powered by a thermonuclear reactor 150 million km away. Even fossil fuels are stored sunlight, captured by ancient photosynthetic organisms and compressed over geological time.\n\n'
        'The Sun has about 5 billion years of hydrogen fuel remaining. When it exhausts its core supply, it will expand into a red giant, engulfing Mercury, Venus, and possibly Earth, before shedding its outer layers and collapsing into a white dwarf. Every atom in your body was forged in a star like the Sun — or in the violent death of a star far more massive. The calcium in your bones, the iron in your blood, the oxygen you breathe: all stellar products, recycled through generations of stellar birth and death.',
    relatedIds: ['solar_planetary_formation', 'solar_habitable_zones', 'planets_earth'],
  ),
  BioEntity(
    id: 'solar_planetary_formation',
    scale: BioScale.solarSystems,
    position: 1,
    name: 'Planetary Formation',
    title: 'From Dust to Worlds',
    shortDescription: 'A collapsing cloud of gas and dust, spinning into a disk, accreting into planetesimals, colliding into protoplanets — world-building takes about 100 million years.',
    longDescription:
        'Solar systems form from molecular clouds — vast regions of interstellar gas and dust, primarily hydrogen and helium with trace amounts of heavier elements produced by previous generations of stars. When a region of a molecular cloud reaches sufficient density (often triggered by a nearby supernova shock wave), it collapses under its own gravity, spinning faster as it contracts (conservation of angular momentum), and flattening into a protoplanetary disk around a central protostar.\n\n'
        'Within this disk, dust grains collide and stick together through electrostatic forces, building up from micrometer-sized particles to kilometer-sized planetesimals over millions of years. Once planetesimals reach sufficient mass, their gravity begins attracting nearby material, accelerating growth in a runaway process. Rocky planets form closer to the star (where temperatures are too high for volatile compounds to condense), while gas giants form beyond the "snow line" where water ice and other volatiles can persist.\n\n'
        'This process connects directly to the atomic and molecular scales explored earlier. The specific elements available — carbon, oxygen, nitrogen, silicon, iron — and their chemical properties determine what kinds of planets can form and what kinds of chemistry can occur on their surfaces. The silicon and iron that form Earth\'s core and mantle, the water that fills its oceans, the carbon and nitrogen that build its life — all were present in the original molecular cloud, sorted and concentrated by the physics of planetary formation.',
    relatedIds: ['solar_earth_system', 'solar_habitable_zones', 'galactic_milky_way'],
  ),
  BioEntity(
    id: 'solar_habitable_zones',
    scale: BioScale.solarSystems,
    position: 2,
    name: 'Habitable Zones',
    title: 'The Goldilocks Region',
    shortDescription: 'Not too hot, not too cold — the orbital band where liquid water can persist on a planet\'s surface, the single most important criterion for life as we know it.',
    longDescription:
        'The habitable zone (HZ) is the range of orbital distances from a star where a planet with sufficient atmospheric pressure could maintain liquid water on its surface. For our Sun, this zone extends roughly from 0.95 to 1.67 AU (Earth orbits at 1.0 AU). But the concept is far more nuanced than simple distance: atmospheric composition, planetary mass, magnetic field strength, tidal heating, and stellar variability all affect whether a planet can actually sustain liquid water.\n\n'
        'Venus, at 0.72 AU, is technically near the inner edge of the Sun\'s habitable zone, but a runaway greenhouse effect has heated its surface to 465 degrees C — hot enough to melt lead. Mars, at 1.52 AU, sits within the outer habitable zone but lost its atmosphere due to its weak gravity and absent magnetic field. Earth succeeds where its neighbors fail not just because of distance but because of a constellation of factors: plate tectonics that recycle carbon, a magnetic field that retains atmosphere, a large moon that stabilizes climate, and an atmosphere with just the right greenhouse effect.\n\n'
        'The concept of habitability is expanding. Subsurface oceans on Jupiter\'s moon Europa and Saturn\'s moon Enceladus — heated by tidal forces, not stellar radiation — suggest that habitable environments may exist far outside traditional habitable zones. Life might not need a star at all, just liquid water, an energy source, and the right chemistry. This possibility multiplies the number of potentially habitable worlds in our galaxy by orders of magnitude.',
    relatedIds: ['solar_earth_system', 'planets_earth', 'planets_exoplanets'],
  ),
  BioEntity(
    id: 'solar_architecture',
    scale: BioScale.solarSystems,
    position: 3,
    name: 'System Architecture',
    title: 'The Orbital Dance',
    shortDescription: 'Eight planets, hundreds of moons, millions of asteroids — our solar system\'s architecture is both typical and unique among the thousands of systems discovered.',
    longDescription:
        'Our solar system\'s architecture — four rocky inner planets, an asteroid belt, four gas/ice giants, and a vast outer reservoir of icy bodies (the Kuiper Belt and Oort Cloud) — was once assumed to be the template for all planetary systems. Exoplanet discoveries have shattered this assumption. Hot Jupiters, super-Earths, mini-Neptunes, and tightly packed systems of multiple rocky worlds have revealed that our configuration is just one of many possible outcomes of planetary formation.\n\n'
        'The stability of our system depends on gravitational resonances and near-misses that play out over billions of years. Jupiter\'s massive gravity both protects the inner planets (by deflecting many comets and asteroids) and threatens them (its gravitational perturbations can destabilize orbits over long timescales). The Late Heavy Bombardment, roughly 3.9 billion years ago, may have been triggered by a gravitational reshuffling of the outer planets — a reminder that our seemingly stable system is a dynamic, evolving structure.\n\n'
        'Each component of the solar system contributes to Earth\'s habitability in ways that connect back to every scale in this app. The asteroid belt delivered water and organic molecules to early Earth. Jupiter shields us from frequent catastrophic impacts. The Moon\'s tidal forces may have helped concentrate prebiotic chemistry in tidal pools. The solar system is not just Earth\'s address — it is the larger organism within which our planet\'s biosphere is embedded.',
    relatedIds: ['solar_earth_system', 'solar_planetary_formation', 'planets_earth'],
  ),
];
